// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file wode/agent/v1/AgentService.proto (package wode.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { InfoRequest, InfoResponse, ReloadRequest, ReloadResponse } from "./AgentService_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wode.agent.v1.AgentService
 */
export const AgentService = {
  typeName: "wode.agent.v1.AgentService",
  methods: {
    /**
     * @generated from rpc wode.agent.v1.AgentService.Info
     */
    info: {
      name: "Info",
      I: InfoRequest,
      O: InfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.agent.v1.AgentService.Reload
     */
    reload: {
      name: "Reload",
      I: ReloadRequest,
      O: ReloadResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
