// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file wode/agent/v1/AgentService.proto (package wode.agent.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wode/agent/v1/AgentService.proto.
 */
export const file_wode_agent_v1_AgentService: GenFile = /*@__PURE__*/
  fileDesc("CiB3b2RlL2FnZW50L3YxL0FnZW50U2VydmljZS5wcm90bxINd29kZS5hZ2VudC52MSINCgtJbmZvUmVxdWVzdCKZAQoMSW5mb1Jlc3BvbnNlEicKA25vdxgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKc3RhcnRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDgoGdXB0aW1lGAMgASgBEhAKCHRpbWV6b25lGAQgASgJEg4KBmxvY2FsZRgFIAEoCSIfCg1SZWxvYWRSZXF1ZXN0Eg4KBnJlYXNvbhgBIAEoCSIhCg5SZWxvYWRSZXNwb25zZRIPCgdtZXNzYWdlGAEgASgJMpYBCgxBZ2VudFNlcnZpY2USPwoESW5mbxIaLndvZGUuYWdlbnQudjEuSW5mb1JlcXVlc3QaGy53b2RlLmFnZW50LnYxLkluZm9SZXNwb25zZRJFCgZSZWxvYWQSHC53b2RlLmFnZW50LnYxLlJlbG9hZFJlcXVlc3QaHS53b2RlLmFnZW50LnYxLlJlbG9hZFJlc3BvbnNlQnwKEWNvbS53b2RlLmFnZW50LnYxQhFBZ2VudFNlcnZpY2VQcm90b1ABogIDV0FYqgINV29kZS5BZ2VudC5WMcoCDVdvZGVcQWdlbnRcVjHiAhlXb2RlXEFnZW50XFYxXEdQQk1ldGFkYXRh6gIPV29kZTo6QWdlbnQ6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message wode.agent.v1.InfoRequest
 */
export type InfoRequest = Message<"wode.agent.v1.InfoRequest"> & {
};

/**
 * Describes the message wode.agent.v1.InfoRequest.
 * Use `create(InfoRequestSchema)` to create a new message.
 */
export const InfoRequestSchema: GenMessage<InfoRequest> = /*@__PURE__*/
  messageDesc(file_wode_agent_v1_AgentService, 0);

/**
 * @generated from message wode.agent.v1.InfoResponse
 */
export type InfoResponse = Message<"wode.agent.v1.InfoResponse"> & {
  /**
   * @generated from field: google.protobuf.Timestamp now = 1;
   */
  now?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 2;
   */
  startedAt?: Timestamp | undefined;

  /**
   * @generated from field: double uptime = 3;
   */
  uptime: number;

  /**
   * @generated from field: string timezone = 4;
   */
  timezone: string;

  /**
   * @generated from field: string locale = 5;
   */
  locale: string;
};

/**
 * Describes the message wode.agent.v1.InfoResponse.
 * Use `create(InfoResponseSchema)` to create a new message.
 */
export const InfoResponseSchema: GenMessage<InfoResponse> = /*@__PURE__*/
  messageDesc(file_wode_agent_v1_AgentService, 1);

/**
 * @generated from message wode.agent.v1.ReloadRequest
 */
export type ReloadRequest = Message<"wode.agent.v1.ReloadRequest"> & {
  /**
   * @generated from field: string reason = 1;
   */
  reason: string;
};

/**
 * Describes the message wode.agent.v1.ReloadRequest.
 * Use `create(ReloadRequestSchema)` to create a new message.
 */
export const ReloadRequestSchema: GenMessage<ReloadRequest> = /*@__PURE__*/
  messageDesc(file_wode_agent_v1_AgentService, 2);

/**
 * @generated from message wode.agent.v1.ReloadResponse
 */
export type ReloadResponse = Message<"wode.agent.v1.ReloadResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message wode.agent.v1.ReloadResponse.
 * Use `create(ReloadResponseSchema)` to create a new message.
 */
export const ReloadResponseSchema: GenMessage<ReloadResponse> = /*@__PURE__*/
  messageDesc(file_wode_agent_v1_AgentService, 3);

/**
 * @generated from service wode.agent.v1.AgentService
 */
export const AgentService: GenService<{
  /**
   * @generated from rpc wode.agent.v1.AgentService.Info
   */
  info: {
    methodKind: "unary";
    input: typeof InfoRequestSchema;
    output: typeof InfoResponseSchema;
  },
  /**
   * @generated from rpc wode.agent.v1.AgentService.Reload
   */
  reload: {
    methodKind: "unary";
    input: typeof ReloadRequestSchema;
    output: typeof ReloadResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wode_agent_v1_AgentService, 0);
