import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { types } from 'mime-types';

const require = createRequire(import.meta.url);
const { version } = JSON.parse(readFileSync(require.resolve('mime-types/package.json'), 'utf8'));
const compareCodePoints = (left, right) => (left < right ? -1 : left > right ? 1 : 0);
const entries = Object.entries(types).sort(([left], [right]) => compareCodePoints(left, right));
const quote = (value) => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
const properties = entries
	.map(([extension, mimeType]) => {
		const key = /^[A-Za-z_$][\w$]*$/.test(extension) ? extension : quote(extension);
		return `\t${key}: ${quote(mimeType)},`;
	})
	.join('\n');
const output = `// Generated by scripts/generateMimeTypes.mjs from mime-types@${version}.\nexport const GeneratedMimeTypes = {\n${properties}\n} as const;\n`;

const target = new URL('../src/fs/mimeTypes.generated.ts', import.meta.url);
if (process.argv.includes('--check')) {
	if (readFileSync(target, 'utf8') !== output) {
		throw new Error('mimeTypes.generated.ts is stale; run generate:fs-mime-types');
	}
} else {
	writeFileSync(target, output);
}
