import { z } from 'zod';
import type { EnumValues } from './schema';

export const ResourceStatus = Object.freeze({
	__proto__: null,
	Active: 'Active',
	Approved: 'Approved',
	Cancelled: 'Cancelled',
	Closed: 'Closed',
	Completed: 'Completed',
	Confirmed: 'Confirmed',
	Contacted: 'Contacted',
	Contacting: 'Contacting',
	Deleted: 'Deleted',
	Denied: 'Denied',
	Disabled: 'Disabled',
	Disqualified: 'Disqualified',
	Draft: 'Draft',
	Enabled: 'Enabled',
	Expired: 'Expired',
	Failed: 'Failed',
	InProgress: 'InProgress',
	Inactive: 'Inactive',
	Lost: 'Lost',
	New: 'New',
	Nurturing: 'Nurturing',
	OnHold: 'OnHold',
	Open: 'Open',
	Pending: 'Pending',
	PendingAcceptance: 'PendingAcceptance',
	PendingApproval: 'PendingApproval',
	PendingConfirmation: 'PendingConfirmation',
	PendingResubmission: 'PendingResubmission',
	Posted: 'Posted',
	Published: 'Published',
	Qualified: 'Qualified',
	Rejected: 'Rejected',
	Submitted: 'Submitted',
	Suspended: 'Suspended',
	Terminated: 'Terminated',
	Unqualified: 'Unqualified',
	Void: 'Void',
	Won: 'Won',
} as const);
export type ResourceStatus = EnumValues<typeof ResourceStatus>;
export const ResourceStatusSchema = z
	.union([
		z.literal(ResourceStatus.Active).describe('活跃'),
		z.literal(ResourceStatus.Approved).describe('已通过'),
		z.literal(ResourceStatus.Cancelled).describe('已取消'),
		z.literal(ResourceStatus.Closed).describe('已关闭'),
		z.literal(ResourceStatus.Completed).describe('已完成'),
		z.literal(ResourceStatus.Confirmed).describe('已确认'),
		z.literal(ResourceStatus.Contacted).describe('已联系'),
		z.literal(ResourceStatus.Contacting).describe('联系中'),
		z.literal(ResourceStatus.Deleted).describe('已删除'),
		z.literal(ResourceStatus.Denied).describe('已拒绝'),
		z.literal(ResourceStatus.Disabled).describe('已禁用'),
		z.literal(ResourceStatus.Disqualified).describe('不合格'),
		z.literal(ResourceStatus.Draft).describe('草稿'),
		z.literal(ResourceStatus.Enabled).describe('已启用'),
		z.literal(ResourceStatus.Expired).describe('已过期'),
		z.literal(ResourceStatus.InProgress).describe('进行中'),
		z.literal(ResourceStatus.Inactive).describe('停用'),
		z.literal(ResourceStatus.Lost).describe('已失去'),
		z.literal(ResourceStatus.New).describe('新建'),
		z.literal(ResourceStatus.Nurturing).describe('培育中'),
		z.literal(ResourceStatus.OnHold).describe('搁置'),
		z.literal(ResourceStatus.Open).describe('开放'),
		z.literal(ResourceStatus.Pending).describe('待审核'),
		z.literal(ResourceStatus.PendingAcceptance).describe('待接受'),
		z.literal(ResourceStatus.PendingApproval).describe('待批准'),
		z.literal(ResourceStatus.PendingConfirmation).describe('待确认'),
		z.literal(ResourceStatus.PendingResubmission).describe('待重新提交'),
		z.literal(ResourceStatus.Posted).describe('已过账'),
		z.literal(ResourceStatus.Published).describe('已发布'),
		z.literal(ResourceStatus.Qualified).describe('已合格'),
		z.literal(ResourceStatus.Rejected).describe('已驳回'),
		z.literal(ResourceStatus.Submitted).describe('已提交'),
		z.literal(ResourceStatus.Suspended).describe('暂停'),
		z.literal(ResourceStatus.Terminated).describe('终止'),
		z.literal(ResourceStatus.Unqualified).describe('未达标'),
		z.literal(ResourceStatus.Void).describe('作废'),
		z.literal(ResourceStatus.Won).describe('已赢得'),
	])
	.meta({ title: 'ResourceStatus', description: '资源状态', type: 'string' });
