packages:
  - 'apps/*'
  - 'packages/*'
  - 'components/*'

allowBuilds:
  '@mongodb-js/zstd': false
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@swc/core': true
  argon2: true
  bcrypt: true
  bufferutil: false
  canvas: true
  esbuild: true
  msw: false
  node-liblzma: false
  protobufjs: false
  puppeteer: false
  sharp: true
  utf-8-validate: false
  workerd: false
catalog:
  '@vitest/browser': ^5.0.1
  '@vitest/browser-playwright': ^5.0.1
  vite: ^8.3.0
  vitest: ^5.0.1
dedupeDirectDeps: true

ignoredOptionalDependencies:
  - fsevents
linkWorkspacePackages: true

minimumReleaseAge: 1200
minimumReleaseAgeExclude:
  - ai
  - shadcn
  - '@ai-sdk/*'
  - '@shadcn/*'
  - '@wener/*'
  - '@storybook/*'
  - '@vitejs/*'
  - vite
  - react
  - react-router
  - storybook
  - '@voidzero-dev/*'
  - typescript
  - '@typescript/*'
  - vitest
  - '@vitest/*'

# Override dotenv version across the entire workspace
overrides:
  dotenv: ^16
  hono-rate-limiter: ^0.5.3
  'ts-add-js-extension>typescript': 5.9.3
  typescript: 7.0.2
  vite: 'catalog:'
  vitest: 'catalog:'

# Package version overrides
packageExtensions:
  dotenv:
    peerDependencies:
      '@types/node': '*'

patchedDependencies:
  ts-node@11.0.0-beta.1: patches/ts-node.patch
peerDependencyRules:
  allowAny:
    - vitest
  allowedVersions:
    vitest: '*'
preferWorkspacePackages: true

saveWorkspaceProtocol: false

strictPeerDependencies: false

updateConfig:
  ignoreDependencies:
    - '@types/node'
    - 'dotenv'
