#:schema node_modules/wrangler/config-schema.json
name = "wener-components"
main = "dist/server/serve-cloudflare.js"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

# Static assets served from dist/public
assets = { directory = "./dist/public", not_found_handling = "single-page-application" }

routes = [
	{ pattern = "ui-components.wener.me", custom_domain = true },
]

[observability]
enabled = true
