// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file wode/resource/dynamic/v1/DynamicResourceService.proto (package wode.resource.dynamic.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteResourceRequest, DeleteResourceResponse, ExecCubeQueryRequest, ExecCubeQueryResponse, ExportResourceRequest, ExportResourceResponse, GetResourceRequest, GetResourceResponse, GetResourceSchemaRequest, GetResourceSchemaResponse, ImportResourceRequest, ImportResourceResponse, ListResourceRequest, ListResourceResponse, ResolveResourceRequest, ResolveResourceResponse, UpdateResourceNotesRequest, UpdateResourceNotesResponse, UpdateResourceRequest, UpdateResourceResponse, UpdateResourceStatusRequest, UpdateResourceStatusResponse, UpdateResourceTagsRequest, UpdateResourceTagsResponse, WatchResourceRequest, WatchResourceResponse } from "./DynamicResourceService_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wode.resource.dynamic.v1.DynamicResourceService
 */
export const DynamicResourceService = {
  typeName: "wode.resource.dynamic.v1.DynamicResourceService",
  methods: {
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.ImportResource
     */
    importResource: {
      name: "ImportResource",
      I: ImportResourceRequest,
      O: ImportResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.ExportResource
     */
    exportResource: {
      name: "ExportResource",
      I: ExportResourceRequest,
      O: ExportResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.GetResourceSchema
     */
    getResourceSchema: {
      name: "GetResourceSchema",
      I: GetResourceSchemaRequest,
      O: GetResourceSchemaResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.GetResource
     */
    getResource: {
      name: "GetResource",
      I: GetResourceRequest,
      O: GetResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.WatchResource
     */
    watchResource: {
      name: "WatchResource",
      I: WatchResourceRequest,
      O: WatchResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.ResolveResource
     */
    resolveResource: {
      name: "ResolveResource",
      I: ResolveResourceRequest,
      O: ResolveResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.ListResource
     */
    listResource: {
      name: "ListResource",
      I: ListResourceRequest,
      O: ListResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.DeleteResource
     */
    deleteResource: {
      name: "DeleteResource",
      I: DeleteResourceRequest,
      O: DeleteResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.UpdateResource
     */
    updateResource: {
      name: "UpdateResource",
      I: UpdateResourceRequest,
      O: UpdateResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.UpdateResourceStatus
     */
    updateResourceStatus: {
      name: "UpdateResourceStatus",
      I: UpdateResourceStatusRequest,
      O: UpdateResourceStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.UpdateResourceTags
     */
    updateResourceTags: {
      name: "UpdateResourceTags",
      I: UpdateResourceTagsRequest,
      O: UpdateResourceTagsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.UpdateResourceNotes
     */
    updateResourceNotes: {
      name: "UpdateResourceNotes",
      I: UpdateResourceNotesRequest,
      O: UpdateResourceNotesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.dynamic.v1.DynamicResourceService.ExecCubeQuery
     */
    execCubeQuery: {
      name: "ExecCubeQuery",
      I: ExecCubeQueryRequest,
      O: ExecCubeQueryResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
