import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { afterEach, test } from 'node:test';

const repoRoot = resolve(import.meta.dirname, '../../..');
const script = resolve(import.meta.dirname, 'check-ui-source-lines.mjs');
const temporaryRoots = [];

afterEach(async () => {
	await Promise.all(temporaryRoots.splice(0).map((path) => rm(path, { force: true, recursive: true })));
});

test('accepts sources at the physical line limit and ignores dependency trees', async () => {
	const root = await createFixture();
	await writeSource(root, 'src/limit.ts', 3);
	await writeSource(root, 'src/module.mts', 3);
	await writeSource(root, 'node_modules/dependency.ts', 4);

	const result = runCheck(root, 3);

	assert.equal(result.status, 0, result.stderr);
	assert.match(result.stdout, /2 TypeScript source files/);
	assert.doesNotMatch(result.stderr, /dependency\.ts/);
});

test('counts CRLF files with a trailing newline by physical lines', async () => {
	const root = await createFixture();
	const destination = join(root, 'src/crlf.ts');
	await mkdir(dirname(destination), { recursive: true });
	await writeFile(destination, 'export const first = 1;\r\nexport const second = 2;\r\n');

	const result = runCheck(root, 2);

	assert.equal(result.status, 0, result.stderr);
});

test('fails generated sources instead of granting a broad exemption', async () => {
	const root = await createFixture();
	await writeSource(root, 'src/routes.gen.ts', 4, '// generated file');

	const result = runCheck(root, 3);

	assert.equal(result.status, 1);
	assert.match(result.stderr, /routes\.gen\.ts: 4 lines \(generated\)/);
});

test('detects a generated header without relying on the file name', async () => {
	const root = await createFixture();
	await writeSource(root, 'src/routes.ts', 4, '// DO NOT EDIT: auto-generated by route tooling');

	const result = runCheck(root, 3);

	assert.equal(result.status, 1);
	assert.match(result.stderr, /routes\.ts: 4 lines \(generated\)/);
});

test('does not classify ordinary generated wording as generated source', async () => {
	const root = await createFixture();
	await writeSource(root, 'src/message.ts', 4, "export const message = 'generated report';");

	const result = runCheck(root, 3);

	assert.equal(result.status, 1);
	assert.match(result.stderr, /message\.ts: 4 lines$/m);
	assert.doesNotMatch(result.stderr, /message\.ts: 4 lines \(generated\)/);
});

test('accepts a generated file as an explicit audit root', async () => {
	const root = await createFixture();
	await writeSource(root, 'src/routes.gen.ts', 3, '// generated file');

	const result = runCheck(join(root, 'src/routes.gen.ts'), 3);

	assert.equal(result.status, 0, result.stderr);
	assert.match(result.stdout, /1 TypeScript source files, 1 generated/);
});

test('scans authored directories with output-like names outside explicit package output paths', async () => {
	const root = await createFixture();
	await writeSource(root, 'src/lib/oversized.ts', 4);
	await writeSource(root, 'src/build/also-oversized.ts', 4);

	const result = runCheck(root, 3);

	assert.equal(result.status, 1);
	assert.match(result.stderr, /src\/lib\/oversized\.ts: 4 lines/);
	assert.match(result.stderr, /src\/build\/also-oversized\.ts: 4 lines/);
});

test('follows TypeScript file symlinks instead of silently skipping them', async () => {
	const root = await createFixture();
	await writeSource(root, 'source/oversized.ts', 4);
	await mkdir(join(root, 'src'), { recursive: true });
	await symlink(join(root, 'source/oversized.ts'), join(root, 'src/linked.ts'));

	const result = runCheck(join(root, 'src'), 3);

	assert.equal(result.status, 1);
	assert.match(result.stderr, /src\/linked\.ts: 4 lines/);
});

test('rejects invalid maximum line configuration', async () => {
	const root = await createFixture();
	const result = runCheck(root, 0);

	assert.notEqual(result.status, 0);
	assert.match(result.stderr, /--max-lines must be a positive integer/);
});

async function createFixture() {
	const root = await mkdtemp(join(tmpdir(), 'wode-ui-source-lines-'));
	temporaryRoots.push(root);
	return root;
}

async function writeSource(root, path, lines, prefix) {
	const destination = join(root, path);
	await mkdir(dirname(destination), { recursive: true });
	const content = Array.from({ length: lines }, (_, index) =>
		index === 0 && prefix ? prefix : `export const value${index} = ${index};`,
	).join('\n');
	await writeFile(destination, content);
}

function runCheck(root, maximumLines) {
	return spawnSync(
		process.execPath,
		[script, '--root', relative(repoRoot, root), '--max-lines', String(maximumLines)],
		{
			cwd: repoRoot,
			encoding: 'utf8',
		},
	);
}
