import type { ComponentType } from 'react';
import {
	PiArrowDown,
	PiArrowLineDown,
	PiArrowLineUp,
	PiArrowsClockwise,
	PiArrowSquareOut,
	PiArrowUp,
	PiCaretDownFill,
	PiCopy,
	PiDotsThreeOutlineVerticalFill,
	PiDownloadSimple,
	PiFolder,
	PiFolders,
	PiListDashes,
	PiMagnifyingGlass,
	PiPlus,
	PiSortAscending,
	PiSortDescending,
	PiSquaresFour,
	PiTrashSimple,
	PiUploadSimple,
} from 'react-icons/pi';

export const ActionIcon = {
	Ascend: PiSortAscending,
	Collapse: PiCaretDownFill,
	Copy: PiCopy,
	Delete: PiTrashSimple,
	Descend: PiSortDescending,
	Download: PiDownloadSimple,
	DropdownIndicator: PiCaretDownFill,
	Expand: PiCaretDownFill,
	GridView: PiSquaresFour,
	KebabMenu: PiDotsThreeOutlineVerticalFill,
	ListView: PiListDashes,
	More: PiDotsThreeOutlineVerticalFill,
	MoveBottom: PiArrowLineDown,
	MoveDown: PiArrowDown,
	MoveFile: PiFolder,
	MoveTop: PiArrowLineUp,
	MoveUp: PiArrowUp,
	Plus: PiPlus,
	Popup: PiArrowSquareOut,
	Refresh: PiArrowsClockwise,
	Reload: PiArrowsClockwise,
	Search: PiMagnifyingGlass,
	Upload: PiUploadSimple,
} as const satisfies Record<string, ComponentType<any>>;

export const AppletIcon = {
	FileManager: PiFolders,
	Dashboard: PiSquaresFour,
} as const satisfies Record<string, ComponentType<any>>;
