// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wode/fs/v1/FileSystemService.proto

package filesystemservicev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wenerme/wode/wogo/proto/wode/fs/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FileSystemServiceName is the fully-qualified name of the FileSystemService service.
	FileSystemServiceName = "wode.fs.v1.FileSystemService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileSystemServiceReaddirProcedure is the fully-qualified name of the FileSystemService's Readdir
	// RPC.
	FileSystemServiceReaddirProcedure = "/wode.fs.v1.FileSystemService/Readdir"
	// FileSystemServiceStatProcedure is the fully-qualified name of the FileSystemService's Stat RPC.
	FileSystemServiceStatProcedure = "/wode.fs.v1.FileSystemService/Stat"
	// FileSystemServiceMkdirProcedure is the fully-qualified name of the FileSystemService's Mkdir RPC.
	FileSystemServiceMkdirProcedure = "/wode.fs.v1.FileSystemService/Mkdir"
	// FileSystemServiceReadFileProcedure is the fully-qualified name of the FileSystemService's
	// ReadFile RPC.
	FileSystemServiceReadFileProcedure = "/wode.fs.v1.FileSystemService/ReadFile"
	// FileSystemServiceWriteFileProcedure is the fully-qualified name of the FileSystemService's
	// WriteFile RPC.
	FileSystemServiceWriteFileProcedure = "/wode.fs.v1.FileSystemService/WriteFile"
	// FileSystemServiceRenameProcedure is the fully-qualified name of the FileSystemService's Rename
	// RPC.
	FileSystemServiceRenameProcedure = "/wode.fs.v1.FileSystemService/Rename"
	// FileSystemServiceExistsProcedure is the fully-qualified name of the FileSystemService's Exists
	// RPC.
	FileSystemServiceExistsProcedure = "/wode.fs.v1.FileSystemService/Exists"
	// FileSystemServiceCopyProcedure is the fully-qualified name of the FileSystemService's Copy RPC.
	FileSystemServiceCopyProcedure = "/wode.fs.v1.FileSystemService/Copy"
	// FileSystemServiceRemoveProcedure is the fully-qualified name of the FileSystemService's Remove
	// RPC.
	FileSystemServiceRemoveProcedure = "/wode.fs.v1.FileSystemService/Remove"
)

// FileSystemServiceClient is a client for the wode.fs.v1.FileSystemService service.
type FileSystemServiceClient interface {
	// List directory contents
	Readdir(context.Context, *v1.ReaddirRequest) (*v1.ReaddirResponse, error)
	// Get file or directory status
	Stat(context.Context, *v1.StatRequest) (*v1.StatResponse, error)
	// Create a directory
	Mkdir(context.Context, *v1.MkdirRequest) (*v1.MkdirResponse, error)
	// Read file contents
	ReadFile(context.Context, *v1.ReadFileRequest) (*v1.ReadFileResponse, error)
	// Write file contents
	WriteFile(context.Context, *v1.WriteFileRequest) (*v1.WriteFileResponse, error)
	// Rename a file or directory
	Rename(context.Context, *v1.RenameRequest) (*v1.RenameResponse, error)
	// Check if a path exists
	Exists(context.Context, *v1.ExistsRequest) (*v1.ExistsResponse, error)
	// Copy a file or directory
	Copy(context.Context, *v1.CopyRequest) (*v1.CopyResponse, error)
	// Remove a file or directory
	Remove(context.Context, *v1.RemoveRequest) (*v1.RemoveResponse, error)
}

// NewFileSystemServiceClient constructs a client for the wode.fs.v1.FileSystemService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileSystemServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileSystemServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fileSystemServiceMethods := v1.File_wode_fs_v1_FileSystemService_proto.Services().ByName("FileSystemService").Methods()
	return &fileSystemServiceClient{
		readdir: connect.NewClient[v1.ReaddirRequest, v1.ReaddirResponse](
			httpClient,
			baseURL+FileSystemServiceReaddirProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Readdir")),
			connect.WithClientOptions(opts...),
		),
		stat: connect.NewClient[v1.StatRequest, v1.StatResponse](
			httpClient,
			baseURL+FileSystemServiceStatProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Stat")),
			connect.WithClientOptions(opts...),
		),
		mkdir: connect.NewClient[v1.MkdirRequest, v1.MkdirResponse](
			httpClient,
			baseURL+FileSystemServiceMkdirProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Mkdir")),
			connect.WithClientOptions(opts...),
		),
		readFile: connect.NewClient[v1.ReadFileRequest, v1.ReadFileResponse](
			httpClient,
			baseURL+FileSystemServiceReadFileProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("ReadFile")),
			connect.WithClientOptions(opts...),
		),
		writeFile: connect.NewClient[v1.WriteFileRequest, v1.WriteFileResponse](
			httpClient,
			baseURL+FileSystemServiceWriteFileProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("WriteFile")),
			connect.WithClientOptions(opts...),
		),
		rename: connect.NewClient[v1.RenameRequest, v1.RenameResponse](
			httpClient,
			baseURL+FileSystemServiceRenameProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Rename")),
			connect.WithClientOptions(opts...),
		),
		exists: connect.NewClient[v1.ExistsRequest, v1.ExistsResponse](
			httpClient,
			baseURL+FileSystemServiceExistsProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Exists")),
			connect.WithClientOptions(opts...),
		),
		copy: connect.NewClient[v1.CopyRequest, v1.CopyResponse](
			httpClient,
			baseURL+FileSystemServiceCopyProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Copy")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[v1.RemoveRequest, v1.RemoveResponse](
			httpClient,
			baseURL+FileSystemServiceRemoveProcedure,
			connect.WithSchema(fileSystemServiceMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileSystemServiceClient implements FileSystemServiceClient.
type fileSystemServiceClient struct {
	readdir   *connect.Client[v1.ReaddirRequest, v1.ReaddirResponse]
	stat      *connect.Client[v1.StatRequest, v1.StatResponse]
	mkdir     *connect.Client[v1.MkdirRequest, v1.MkdirResponse]
	readFile  *connect.Client[v1.ReadFileRequest, v1.ReadFileResponse]
	writeFile *connect.Client[v1.WriteFileRequest, v1.WriteFileResponse]
	rename    *connect.Client[v1.RenameRequest, v1.RenameResponse]
	exists    *connect.Client[v1.ExistsRequest, v1.ExistsResponse]
	copy      *connect.Client[v1.CopyRequest, v1.CopyResponse]
	remove    *connect.Client[v1.RemoveRequest, v1.RemoveResponse]
}

// Readdir calls wode.fs.v1.FileSystemService.Readdir.
func (c *fileSystemServiceClient) Readdir(ctx context.Context, req *v1.ReaddirRequest) (*v1.ReaddirResponse, error) {
	response, err := c.readdir.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Stat calls wode.fs.v1.FileSystemService.Stat.
func (c *fileSystemServiceClient) Stat(ctx context.Context, req *v1.StatRequest) (*v1.StatResponse, error) {
	response, err := c.stat.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Mkdir calls wode.fs.v1.FileSystemService.Mkdir.
func (c *fileSystemServiceClient) Mkdir(ctx context.Context, req *v1.MkdirRequest) (*v1.MkdirResponse, error) {
	response, err := c.mkdir.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ReadFile calls wode.fs.v1.FileSystemService.ReadFile.
func (c *fileSystemServiceClient) ReadFile(ctx context.Context, req *v1.ReadFileRequest) (*v1.ReadFileResponse, error) {
	response, err := c.readFile.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WriteFile calls wode.fs.v1.FileSystemService.WriteFile.
func (c *fileSystemServiceClient) WriteFile(ctx context.Context, req *v1.WriteFileRequest) (*v1.WriteFileResponse, error) {
	response, err := c.writeFile.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Rename calls wode.fs.v1.FileSystemService.Rename.
func (c *fileSystemServiceClient) Rename(ctx context.Context, req *v1.RenameRequest) (*v1.RenameResponse, error) {
	response, err := c.rename.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Exists calls wode.fs.v1.FileSystemService.Exists.
func (c *fileSystemServiceClient) Exists(ctx context.Context, req *v1.ExistsRequest) (*v1.ExistsResponse, error) {
	response, err := c.exists.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Copy calls wode.fs.v1.FileSystemService.Copy.
func (c *fileSystemServiceClient) Copy(ctx context.Context, req *v1.CopyRequest) (*v1.CopyResponse, error) {
	response, err := c.copy.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Remove calls wode.fs.v1.FileSystemService.Remove.
func (c *fileSystemServiceClient) Remove(ctx context.Context, req *v1.RemoveRequest) (*v1.RemoveResponse, error) {
	response, err := c.remove.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// FileSystemServiceHandler is an implementation of the wode.fs.v1.FileSystemService service.
type FileSystemServiceHandler interface {
	// List directory contents
	Readdir(context.Context, *v1.ReaddirRequest) (*v1.ReaddirResponse, error)
	// Get file or directory status
	Stat(context.Context, *v1.StatRequest) (*v1.StatResponse, error)
	// Create a directory
	Mkdir(context.Context, *v1.MkdirRequest) (*v1.MkdirResponse, error)
	// Read file contents
	ReadFile(context.Context, *v1.ReadFileRequest) (*v1.ReadFileResponse, error)
	// Write file contents
	WriteFile(context.Context, *v1.WriteFileRequest) (*v1.WriteFileResponse, error)
	// Rename a file or directory
	Rename(context.Context, *v1.RenameRequest) (*v1.RenameResponse, error)
	// Check if a path exists
	Exists(context.Context, *v1.ExistsRequest) (*v1.ExistsResponse, error)
	// Copy a file or directory
	Copy(context.Context, *v1.CopyRequest) (*v1.CopyResponse, error)
	// Remove a file or directory
	Remove(context.Context, *v1.RemoveRequest) (*v1.RemoveResponse, error)
}

// NewFileSystemServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileSystemServiceHandler(svc FileSystemServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileSystemServiceMethods := v1.File_wode_fs_v1_FileSystemService_proto.Services().ByName("FileSystemService").Methods()
	fileSystemServiceReaddirHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceReaddirProcedure,
		svc.Readdir,
		connect.WithSchema(fileSystemServiceMethods.ByName("Readdir")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceStatHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceStatProcedure,
		svc.Stat,
		connect.WithSchema(fileSystemServiceMethods.ByName("Stat")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceMkdirHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceMkdirProcedure,
		svc.Mkdir,
		connect.WithSchema(fileSystemServiceMethods.ByName("Mkdir")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceReadFileHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceReadFileProcedure,
		svc.ReadFile,
		connect.WithSchema(fileSystemServiceMethods.ByName("ReadFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceWriteFileHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceWriteFileProcedure,
		svc.WriteFile,
		connect.WithSchema(fileSystemServiceMethods.ByName("WriteFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceRenameHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceRenameProcedure,
		svc.Rename,
		connect.WithSchema(fileSystemServiceMethods.ByName("Rename")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceExistsHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceExistsProcedure,
		svc.Exists,
		connect.WithSchema(fileSystemServiceMethods.ByName("Exists")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceCopyHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceCopyProcedure,
		svc.Copy,
		connect.WithSchema(fileSystemServiceMethods.ByName("Copy")),
		connect.WithHandlerOptions(opts...),
	)
	fileSystemServiceRemoveHandler := connect.NewUnaryHandlerSimple(
		FileSystemServiceRemoveProcedure,
		svc.Remove,
		connect.WithSchema(fileSystemServiceMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wode.fs.v1.FileSystemService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileSystemServiceReaddirProcedure:
			fileSystemServiceReaddirHandler.ServeHTTP(w, r)
		case FileSystemServiceStatProcedure:
			fileSystemServiceStatHandler.ServeHTTP(w, r)
		case FileSystemServiceMkdirProcedure:
			fileSystemServiceMkdirHandler.ServeHTTP(w, r)
		case FileSystemServiceReadFileProcedure:
			fileSystemServiceReadFileHandler.ServeHTTP(w, r)
		case FileSystemServiceWriteFileProcedure:
			fileSystemServiceWriteFileHandler.ServeHTTP(w, r)
		case FileSystemServiceRenameProcedure:
			fileSystemServiceRenameHandler.ServeHTTP(w, r)
		case FileSystemServiceExistsProcedure:
			fileSystemServiceExistsHandler.ServeHTTP(w, r)
		case FileSystemServiceCopyProcedure:
			fileSystemServiceCopyHandler.ServeHTTP(w, r)
		case FileSystemServiceRemoveProcedure:
			fileSystemServiceRemoveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileSystemServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileSystemServiceHandler struct{}

func (UnimplementedFileSystemServiceHandler) Readdir(context.Context, *v1.ReaddirRequest) (*v1.ReaddirResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Readdir is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) Stat(context.Context, *v1.StatRequest) (*v1.StatResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Stat is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) Mkdir(context.Context, *v1.MkdirRequest) (*v1.MkdirResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Mkdir is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) ReadFile(context.Context, *v1.ReadFileRequest) (*v1.ReadFileResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.ReadFile is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) WriteFile(context.Context, *v1.WriteFileRequest) (*v1.WriteFileResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.WriteFile is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) Rename(context.Context, *v1.RenameRequest) (*v1.RenameResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Rename is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) Exists(context.Context, *v1.ExistsRequest) (*v1.ExistsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Exists is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) Copy(context.Context, *v1.CopyRequest) (*v1.CopyResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Copy is not implemented"))
}

func (UnimplementedFileSystemServiceHandler) Remove(context.Context, *v1.RemoveRequest) (*v1.RemoveResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("wode.fs.v1.FileSystemService.Remove is not implemented"))
}
