'use client';
import { Maximize2, Minimize2, Minus, X } from 'lucide-react';
import type { ComponentPropsWithRef } from 'react';
import { cn } from '../../utils';
import type { WindowFrameProps } from './WindowFrame';
import { WINDOW_MANAGER_DRAG_HANDLE_CLASS, WindowManagerContent, WindowManagerFrame, WindowManagerMenu, WindowManagerStatusBar, WindowManagerToolbar } from './WindowManagerChrome';
export function MacOSWindowFrame({ actions, active, content, icon, menuItems, mode, overlayZIndex, statusBar, title, titleId, toolbar, win, onClose, onFullscreen, onMaximize, onMinimize, onToggleMaximize, ...props }: WindowFrameProps) { return <WindowManagerFrame {...props} active={active} data-window-frame-style='macos' mode={mode} className={cn('rounded-md', props.className)}><header id={titleId} className={cn(WINDOW_MANAGER_DRAG_HANDLE_CLASS, 'bg-base-200/80 flex h-7 cursor-default items-center gap-2 rounded-t-md px-1.5 select-none')} onDoubleClick={onToggleMaximize}><MacOSWindowControls canClose={win.capabilities.close} canMaximize={win.capabilities.maximize} canMinimize={win.capabilities.minimize} maximized={mode === 'maximized'} onClose={onClose} onMaximize={onMaximize} onMinimize={onMinimize} /><div className='min-w-0 flex-1 truncate px-1 text-center text-xs font-medium'>{title}</div><div className='flex w-16 shrink-0 items-center justify-end gap-1' data-window-drag-cancel>{icon ? <span className='text-base-content/55 size-4'>{icon}</span> : null}<WindowManagerExtraControls variant='macos' menuItems={menuItems} overlayZIndex={overlayZIndex} pinned={win.pinned} fullscreen={mode === 'fullscreen'} canFullscreen={win.capabilities.fullscreen} onFullscreen={onFullscreen} onPinnedChange={(pinned) => actions.setPinned(win.id, pinned)} /></div></header>{toolbar ? <WindowManagerToolbar>{toolbar}</WindowManagerToolbar> : null}<WindowManagerContent>{content}</WindowManagerContent>{statusBar ? <WindowManagerStatusBar>{statusBar}</WindowManagerStatusBar> : null}</WindowManagerFrame>; }
function MacOSWindowControls({ canClose, canMaximize, canMinimize, maximized, onClose, onMaximize, onMinimize }: { canClose: boolean; canMaximize: boolean; canMinimize: boolean; maximized: boolean; onClose: () => void; onMaximize: () => void; onMinimize: () => void }) { return <div className='group/window-controls flex shrink-0 items-center gap-1.5' data-window-drag-cancel><MacOSWindowControl action='close' label='关闭' disabled={!canClose} onClick={onClose}><X className='size-2.5' /></MacOSWindowControl><MacOSWindowControl action='minimize' label='最小化' disabled={!canMinimize} onClick={onMinimize}><Minus className='size-2.5' /></MacOSWindowControl><MacOSWindowControl action='maximize' label={maximized ? '还原' : '最大化'} disabled={!canMaximize} onClick={onMaximize}>{maximized ? <Minimize2 className='size-2.5' /> : <Maximize2 className='size-2.5' />}</MacOSWindowControl></div>; }
function MacOSWindowControl({ action, className, label, ...props }: ComponentPropsWithRef<'button'> & { action: string; label: string }) { return <button {...props} aria-label={label} className={cn('grid size-3.5 place-items-center rounded-full bg-gray-300 text-black/0 transition-colors hover:text-black/65', 'group-hover/window-controls:bg-(--window-control-color)', 'group-hover/window-controls:text-black/65', 'group-focus-within/window-controls:text-black/65', 'group-focus-within/window:bg-(--window-control-color)', action === 'close' && '[--window-control-color:#f34f4f]', action === 'minimize' && '[--window-control-color:#f3b95d]', action === 'maximize' && '[--window-control-color:#3ab54a]', className)} type='button' />; }
export function WindowManagerExtraControls({ canFullscreen, fullscreen, menuItems, onFullscreen, onPinnedChange, overlayZIndex, pinned, variant }: Pick<WindowFrameProps, 'menuItems' | 'overlayZIndex'> & { pinned: boolean; canFullscreen: boolean; fullscreen: boolean; onFullscreen: () => void; onPinnedChange: (pinned: boolean) => void; variant: 'macos' | 'windows' }) { const controlClassName = cn('hover:bg-base-300/80 focus-visible:ring-primary grid place-items-center rounded-sm focus-visible:z-10 focus-visible:ring-2 focus-visible:outline-none', variant === 'macos' ? 'size-6' : 'size-8'); return <div className='flex items-center gap-0.5' data-window-drag-cancel><WindowManagerMenu canFullscreen={canFullscreen} fullscreen={fullscreen} pinned={pinned} triggerClassName={controlClassName} zIndex={overlayZIndex} onFullscreen={onFullscreen} onPinnedChange={onPinnedChange}>{menuItems}</WindowManagerMenu></div>; }
