'use client';
import { Resizable, type ResizeDirection } from 're-resizable';
import { type CSSProperties, type ReactNode, type PointerEvent as ReactPointerEvent, useEffect, useRef, useState } from 'react';
import { getWindowManagerConstrainedResize, getWindowManagerDragPosition, type WindowManagerMotionBounds } from './WindowManagerMotionGeometry';
export type WindowManagerMotionSurfaceProps = { cancel?: string; children: ReactNode; disableDragging?: boolean; dragHandleClassName?: string; enableResizing?: boolean; interactionKey?: string | number; maxHeight: number; maxWidth: number; minHeight: number; minWidth: number; movementBounds: WindowManagerMotionBounds; onMoveStart?: () => void; onMoveStop?: (position: { x: number; y: number }) => void; onResizeStart?: () => void; onResizeStop?: (value: WindowManagerMotionBounds) => void; position: { x: number; y: number }; size: { height: number; width: number }; style?: CSSProperties };
type DragSession = { maxX: number; maxY: number; minX: number; minY: number; originX: number; originY: number; pointerId: number; startX: number; startY: number };
export function WindowManagerMotionSurface({ cancel, children, disableDragging = false, dragHandleClassName, enableResizing = true, interactionKey = 'default', maxHeight, maxWidth, minHeight, minWidth, movementBounds, onMoveStart, onMoveStop, onResizeStart, onResizeStop, position, size, style }: WindowManagerMotionSurfaceProps) {
	const nodeRef = useRef<HTMLDivElement | null>(null); const activity = useRef<'drag' | 'resize' | undefined>(undefined); const dragSession = useRef<DragSession | undefined>(undefined); const latestPosition = useRef(position); const previousInteractionKey = useRef(interactionKey); const resizeOrigin = useRef<WindowManagerMotionBounds>({ ...position, ...size }); const [visualPosition, setVisualPosition] = useState(position); const [visualSize, setVisualSize] = useState(size);
	useEffect(() => { if (previousInteractionKey.current === interactionKey) return; previousInteractionKey.current = interactionKey; const pointerId = dragSession.current?.pointerId; dragSession.current = undefined; activity.current = undefined; if (pointerId !== undefined && nodeRef.current?.hasPointerCapture(pointerId)) nodeRef.current.releasePointerCapture(pointerId); latestPosition.current = position; setVisualPosition(position); setVisualSize(size); }, [interactionKey, position, size]);
	useEffect(() => { if (activity.current) return; latestPosition.current = position; setVisualPosition(position); }, [position]); useEffect(() => { if (!activity.current) setVisualSize(size); }, [size]);
	const startDrag = (event: ReactPointerEvent<HTMLDivElement>) => { if (disableDragging || event.button !== 0 || !nodeRef.current) return; const target = event.target instanceof Element ? event.target : undefined; if (!target || (dragHandleClassName && !target.closest(`.${dragHandleClassName}`)) || (cancel && target.closest(cancel))) return; event.preventDefault(); nodeRef.current.setPointerCapture(event.pointerId); dragSession.current = { pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, originX: visualPosition.x, originY: visualPosition.y, minX: movementBounds.x, minY: movementBounds.y, maxX: Math.max(movementBounds.x, movementBounds.x + movementBounds.width - visualSize.width), maxY: Math.max(movementBounds.y, movementBounds.y + movementBounds.height - visualSize.height) }; activity.current = 'drag'; onMoveStart?.(); };
	const moveDrag = (event: ReactPointerEvent<HTMLDivElement>) => { const session = dragSession.current; if (!session || session.pointerId !== event.pointerId) return; const next = getWindowManagerDragPosition(session, { x: event.clientX, y: event.clientY }); latestPosition.current = next; setVisualPosition(next); };
	const stopDrag = (event: ReactPointerEvent<HTMLDivElement>) => { const session = dragSession.current; if (!session || session.pointerId !== event.pointerId) return; dragSession.current = undefined; activity.current = undefined; if (nodeRef.current?.hasPointerCapture(event.pointerId)) nodeRef.current.releasePointerCapture(event.pointerId); onMoveStop?.(latestPosition.current); };
	const constrainResize = (direction: ResizeDirection, requested: { height: number; width: number }) => getWindowManagerConstrainedResize({ bounds: movementBounds, direction, maxHeight, maxWidth, minHeight, minWidth, origin: resizeOrigin.current, requested });
	return <div ref={nodeRef} style={{ position: 'absolute', top: 0, left: 0, width: visualSize.width, height: visualSize.height, transform: `translate(${visualPosition.x}px, ${visualPosition.y}px)`, ...style }} onPointerCancel={stopDrag} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={stopDrag}><Resizable enable={enableResizing ? undefined : false} minHeight={minHeight} minWidth={minWidth} maxHeight={maxHeight} maxWidth={maxWidth} size={visualSize} style={{ overflow: 'visible' }} onResizeStart={() => { activity.current = 'resize'; resizeOrigin.current = { ...visualPosition, ...visualSize }; onResizeStart?.(); }} onResize={(_event, direction, element) => { if (activity.current !== 'resize') return; const next = constrainResize(direction, { width: element.offsetWidth, height: element.offsetHeight }); latestPosition.current = next; setVisualPosition({ x: next.x, y: next.y }); setVisualSize({ width: next.width, height: next.height }); }} onResizeStop={(_event, direction, element) => { if (activity.current !== 'resize') return; activity.current = undefined; const next = constrainResize(direction, { width: element.offsetWidth, height: element.offsetHeight }); latestPosition.current = next; setVisualPosition({ x: next.x, y: next.y }); setVisualSize({ width: next.width, height: next.height }); onResizeStop?.(next); }}>{children}</Resizable></div>;
}
