'use client';
import { Minimize2, Minus, Square, X } from 'lucide-react';
import type { ComponentPropsWithRef } from 'react';
import { cn } from '../../utils';
import { WindowManagerExtraControls } from './MacOSWindowFrame';
import type { WindowFrameProps } from './WindowFrame';
import { WINDOW_MANAGER_DRAG_HANDLE_CLASS, WindowManagerContent, WindowManagerFrame, WindowManagerStatusBar, WindowManagerToolbar } from './WindowManagerChrome';
export function WindowsWindowFrame({ actions, active, content, icon, menuItems, mode, overlayZIndex, statusBar, title, titleId, toolbar, win, onClose, onFullscreen, onMaximize, onMinimize, onToggleMaximize, ...props }: WindowFrameProps) { return <WindowManagerFrame {...props} active={active} data-window-frame-style='windows' mode={mode} className={cn('rounded-sm', props.className)}><header id={titleId} className={cn(WINDOW_MANAGER_DRAG_HANDLE_CLASS, 'bg-base-200/80 flex h-7 cursor-default items-center pl-2 select-none')} onDoubleClick={onToggleMaximize}>{icon ? <span className='text-base-content/60 mr-1 grid size-4 shrink-0 place-items-center'>{icon}</span> : null}<div className='min-w-0 flex-1 truncate px-1 text-xs font-medium'>{title}</div><div className='flex h-full items-center' data-window-drag-cancel><WindowManagerExtraControls variant='windows' menuItems={menuItems} overlayZIndex={overlayZIndex} pinned={win.pinned} canFullscreen={win.capabilities.fullscreen} fullscreen={mode === 'fullscreen'} onFullscreen={onFullscreen} onPinnedChange={(pinned) => actions.setPinned(win.id, pinned)} /><WindowsWindowControls canClose={win.capabilities.close} canMaximize={win.capabilities.maximize} canMinimize={win.capabilities.minimize} maximized={mode === 'maximized'} onClose={onClose} onMaximize={onMaximize} onMinimize={onMinimize} /></div></header>{toolbar ? <WindowManagerToolbar>{toolbar}</WindowManagerToolbar> : null}<WindowManagerContent>{content}</WindowManagerContent>{statusBar ? <WindowManagerStatusBar>{statusBar}</WindowManagerStatusBar> : null}</WindowManagerFrame>; }
function WindowsWindowControls({ canClose, canMaximize, canMinimize, maximized, onClose, onMaximize, onMinimize }: { canClose: boolean; canMaximize: boolean; canMinimize: boolean; maximized: boolean; onClose: () => void; onMaximize: () => void; onMinimize: () => void }) { return <div className='flex h-full items-center' data-window-drag-cancel><WindowsWindowControl label='最小化' disabled={!canMinimize} onClick={onMinimize}><Minus className='size-3.5' /></WindowsWindowControl><WindowsWindowControl label={maximized ? '还原' : '最大化'} disabled={!canMaximize} onClick={onMaximize}>{maximized ? <Minimize2 className='size-3.5' /> : <Square className='size-3' />}</WindowsWindowControl><WindowsWindowControl label='关闭' disabled={!canClose} className='hover:bg-error hover:text-error-content' onClick={onClose}><X className='size-3.5' /></WindowsWindowControl></div>; }
function WindowsWindowControl({ className, label, ...props }: ComponentPropsWithRef<'button'> & { label: string }) { return <button {...props} aria-label={label} type='button' className={cn('grid h-full w-9 place-items-center hover:bg-base-300/80 focus-visible:z-10 focus-visible:ring-2 focus-visible:ring-primary focus-visible:outline-none', className)} />; }
