'use client';
import { Menu as BaseMenu } from '@base-ui/react/menu';
import { AppWindow, Focus, Minus, PanelsTopLeft, X } from 'lucide-react';
import type { ComponentPropsWithRef, ReactNode } from 'react';
import { useShallow } from 'zustand/react/shallow';
import { cn } from '../../utils';
import { getWindowRenderData } from './showWindow';
import { WindowManagerMenuItem, WindowManagerMenuPortal, WindowManagerMenuSeparator, type WindowManagerPortalContainer } from './WindowManagerChrome';
import { useWindowManager } from './WindowManagerContext';
import type { ManagedWindow, WindowManagerActions, WindowManagerDockPosition } from './WindowManagerTypes';
export const WINDOW_MANAGER_DOCK_Z_INDEX = 9_000;
export type WindowManagerDockItemRenderContext = { active: boolean; icon: ReactNode; minimized: boolean; win: ManagedWindow };
export type WindowManagerDockProps = ComponentPropsWithRef<'nav'> & { leading?: ReactNode; menuZIndex?: number; minimizeActiveOnClick?: boolean; portalContainer?: WindowManagerPortalContainer; renderIcon?: (win: ManagedWindow) => ReactNode; renderItem?: (context: WindowManagerDockItemRenderContext) => ReactNode; showActions?: boolean; trailing?: ReactNode };
export function WindowManagerDock({ className, leading, menuZIndex = WINDOW_MANAGER_DOCK_Z_INDEX + 1, minimizeActiveOnClick = true, portalContainer, renderIcon = defaultWindowIcon, renderItem, showActions = true, style, trailing, ...props }: WindowManagerDockProps) {
	const { actions, activeId, dock, dockOrder, fullscreen, windowById } = useWindowManager(useShallow((state) => ({ actions: state.actions, activeId: state.activeId, dock: state.workspace.dock, dockOrder: state.dockOrder, fullscreen: state.order.some((id) => state.windows[id]?.mode === 'fullscreen'), windowById: state.windows })));
	if (!dock.visible || fullscreen) return null; const windows = dockOrder.flatMap((id) => { const win = windowById[id]; return win?.showInDock ? [win] : []; }); const managedWindows = Object.values(windowById); const vertical = dock.position !== 'bottom'; const dockStyle = vertical ? { width: dock.size } : { height: dock.size };
	return <nav aria-label='Window dock' data-position={dock.position} className={cn('pointer-events-auto border-base-300 bg-base-100/95 absolute flex items-center border backdrop-blur', dock.position === 'bottom' && 'inset-x-0 bottom-0 flex-row px-2', dock.position === 'left' && 'inset-y-0 left-0 flex-col py-2', dock.position === 'right' && 'inset-y-0 right-0 flex-col py-2', className)} style={{ zIndex: WINDOW_MANAGER_DOCK_Z_INDEX, ...dockStyle, ...style }} {...props}>{leading}{showActions ? <WindowManagerDockMenu actions={actions} active={activeId ? windowById[activeId] : undefined} canCloseAny={managedWindows.some((win) => win.capabilities.close)} canMinimizeAny={managedWindows.some((win) => win.mode !== 'minimized' && win.capabilities.minimize)} count={managedWindows.length} position={dock.position} portalContainer={portalContainer} zIndex={menuZIndex} /> : null}<div className={cn('flex min-h-0 min-w-0 flex-1 items-center gap-1 overflow-auto', vertical ? 'flex-col px-1 py-2' : 'flex-row px-2 py-1')}>{windows.map((win) => { const active = activeId === win.id && win.mode !== 'minimized'; const icon = getWindowRenderData(win)?.icon ?? renderIcon(win); const context = { active, minimized: win.mode === 'minimized', icon, win }; return <button key={win.id} type='button' aria-label={`${win.title}${win.mode === 'minimized' ? ', minimized' : ''}`} aria-pressed={active} title={win.title} data-active={active || undefined} data-mode={win.mode} className={cn('hover:bg-base-200 relative grid size-9 shrink-0 place-items-center rounded-sm', 'focus-visible:ring-primary focus-visible:ring-2 focus-visible:outline-none', 'data-[active=true]:bg-primary/12 data-[active=true]:text-primary', 'data-[mode=minimized]:opacity-55')} onClick={() => { if (win.mode === 'minimized') actions.restore(win.id); else if (active && minimizeActiveOnClick) actions.minimize(win.id); else actions.focus(win.id); }}>{renderItem ? renderItem(context) : icon}<span aria-hidden='true' className={cn('bg-primary absolute rounded-full opacity-0 data-[active=true]:opacity-100', vertical ? 'top-1 bottom-1 left-0 w-0.5' : 'inset-x-1 bottom-0 h-0.5')} data-active={active || undefined} /></button>; })}{windows.length === 0 ? <AppWindow aria-hidden='true' className='text-base-content/30 size-4' /> : null}</div>{trailing}</nav>;
}
type WindowManagerDockMenuProps = { actions: WindowManagerActions; active?: ManagedWindow; canCloseAny: boolean; canMinimizeAny: boolean; count: number; position: WindowManagerDockPosition; portalContainer?: WindowManagerPortalContainer; zIndex: number };
function WindowManagerDockMenu({ actions, active, canCloseAny, canMinimizeAny, count, position, portalContainer, zIndex }: WindowManagerDockMenuProps) { const side = position === 'right' ? 'left' : position === 'left' ? 'right' : 'top'; return <BaseMenu.Root><BaseMenu.Trigger aria-label='Window actions' title='Window actions' className='hover:bg-base-200 focus-visible:ring-primary grid size-8 shrink-0 place-items-center rounded-sm focus-visible:ring-2 focus-visible:outline-none'><PanelsTopLeft className='size-4' /></BaseMenu.Trigger><WindowManagerMenuPortal container={portalContainer}><BaseMenu.Positioner align='start' side={side} sideOffset={6} className='outline-none' style={{ zIndex }}><BaseMenu.Popup className='border-base-300 bg-base-100 text-base-content min-w-48 rounded-md border p-1 shadow-xl outline-none'><BaseMenu.Group><BaseMenu.GroupLabel className='text-base-content/55 px-2 py-1 text-xs'>Active window</BaseMenu.GroupLabel><WindowManagerMenuItem disabled={active?.mode !== 'normal' || !active?.capabilities.move} onClick={() => active && actions.center(active.id)}><Focus className='size-4' /><span>Center window</span></WindowManagerMenuItem><WindowManagerMenuItem disabled={!active?.capabilities.close} onClick={() => active && actions.close(active.id)}><X className='size-4' /><span>Close active window</span></WindowManagerMenuItem></BaseMenu.Group><WindowManagerMenuSeparator /><BaseMenu.Group><BaseMenu.GroupLabel className='text-base-content/55 px-2 py-1 text-xs'>Window management ({count})</BaseMenu.GroupLabel><WindowManagerMenuItem disabled={!canMinimizeAny} onClick={actions.minimizeAll}><Minus className='size-4' /><span>Minimize all windows</span></WindowManagerMenuItem><WindowManagerMenuItem disabled={!canCloseAny} onClick={actions.closeAll}><X className='size-4' /><span>Close all windows</span></WindowManagerMenuItem></BaseMenu.Group></BaseMenu.Popup></BaseMenu.Positioner></WindowManagerMenuPortal></BaseMenu.Root>; }
function defaultWindowIcon(win: ManagedWindow) { return win.icon ? <span className='max-w-7 truncate text-xs font-semibold'>{win.icon}</span> : <span className='text-xs font-semibold'>{win.title.trim().slice(0, 1).toUpperCase() || 'W'}</span>; }
