// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file wode/agent/host/v1/NetworkAgentService.proto (package wode.agent.host.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file wode/agent/host/v1/NetworkAgentService.proto.
 */
export const file_wode_agent_host_v1_NetworkAgentService: GenFile = /*@__PURE__*/
  fileDesc("Cix3b2RlL2FnZW50L2hvc3QvdjEvTmV0d29ya0FnZW50U2VydmljZS5wcm90bxISd29kZS5hZ2VudC5ob3N0LnYxIh8KD0ljbXBQaW5nUmVxdWVzdBIMCgRob3N0GAEgASgJIkgKEEljbXBQaW5nUmVzcG9uc2USDAoEaG9zdBgBIAEoCRILCgNzZXEYAiABKAUSCwoDdHRsGAMgASgCEgwKBHRpbWUYBCABKAIiIgoSUmVzb2x2ZU5hbWVSZXF1ZXN0EgwKBG5hbWUYASABKAkiNgoTUmVzb2x2ZU5hbWVSZXNwb25zZRIMCgRuYW1lGAEgASgJEhEKCWFkZHJlc3NlcxgCIAMoCTLOAQoTTmV0d29ya0FnZW50U2VydmljZRJXCghJY21wUGluZxIjLndvZGUuYWdlbnQuaG9zdC52MS5JY21wUGluZ1JlcXVlc3QaJC53b2RlLmFnZW50Lmhvc3QudjEuSWNtcFBpbmdSZXNwb25zZTABEl4KC1Jlc29sdmVOYW1lEiYud29kZS5hZ2VudC5ob3N0LnYxLlJlc29sdmVOYW1lUmVxdWVzdBonLndvZGUuYWdlbnQuaG9zdC52MS5SZXNvbHZlTmFtZVJlc3BvbnNlQp0BChZjb20ud29kZS5hZ2VudC5ob3N0LnYxQhhOZXR3b3JrQWdlbnRTZXJ2aWNlUHJvdG9QAaICA1dBSKoCEldvZGUuQWdlbnQuSG9zdC5WMcoCEldvZGVcQWdlbnRcSG9zdFxWMeICHldvZGVcQWdlbnRcSG9zdFxWMVxHUEJNZXRhZGF0YeoCFVdvZGU6OkFnZW50OjpIb3N0OjpWMWIGcHJvdG8z");

/**
 * @generated from message wode.agent.host.v1.IcmpPingRequest
 */
export type IcmpPingRequest = Message<"wode.agent.host.v1.IcmpPingRequest"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;
};

/**
 * Describes the message wode.agent.host.v1.IcmpPingRequest.
 * Use `create(IcmpPingRequestSchema)` to create a new message.
 */
export const IcmpPingRequestSchema: GenMessage<IcmpPingRequest> = /*@__PURE__*/
  messageDesc(file_wode_agent_host_v1_NetworkAgentService, 0);

/**
 * @generated from message wode.agent.host.v1.IcmpPingResponse
 */
export type IcmpPingResponse = Message<"wode.agent.host.v1.IcmpPingResponse"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: int32 seq = 2;
   */
  seq: number;

  /**
   * @generated from field: float ttl = 3;
   */
  ttl: number;

  /**
   * @generated from field: float time = 4;
   */
  time: number;
};

/**
 * Describes the message wode.agent.host.v1.IcmpPingResponse.
 * Use `create(IcmpPingResponseSchema)` to create a new message.
 */
export const IcmpPingResponseSchema: GenMessage<IcmpPingResponse> = /*@__PURE__*/
  messageDesc(file_wode_agent_host_v1_NetworkAgentService, 1);

/**
 * @generated from message wode.agent.host.v1.ResolveNameRequest
 */
export type ResolveNameRequest = Message<"wode.agent.host.v1.ResolveNameRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message wode.agent.host.v1.ResolveNameRequest.
 * Use `create(ResolveNameRequestSchema)` to create a new message.
 */
export const ResolveNameRequestSchema: GenMessage<ResolveNameRequest> = /*@__PURE__*/
  messageDesc(file_wode_agent_host_v1_NetworkAgentService, 2);

/**
 * @generated from message wode.agent.host.v1.ResolveNameResponse
 */
export type ResolveNameResponse = Message<"wode.agent.host.v1.ResolveNameResponse"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated string addresses = 2;
   */
  addresses: string[];
};

/**
 * Describes the message wode.agent.host.v1.ResolveNameResponse.
 * Use `create(ResolveNameResponseSchema)` to create a new message.
 */
export const ResolveNameResponseSchema: GenMessage<ResolveNameResponse> = /*@__PURE__*/
  messageDesc(file_wode_agent_host_v1_NetworkAgentService, 3);

/**
 * @generated from service wode.agent.host.v1.NetworkAgentService
 */
export const NetworkAgentService: GenService<{
  /**
   * @generated from rpc wode.agent.host.v1.NetworkAgentService.IcmpPing
   */
  icmpPing: {
    methodKind: "server_streaming";
    input: typeof IcmpPingRequestSchema;
    output: typeof IcmpPingResponseSchema;
  },
  /**
   * @generated from rpc wode.agent.host.v1.NetworkAgentService.ResolveName
   */
  resolveName: {
    methodKind: "unary";
    input: typeof ResolveNameRequestSchema;
    output: typeof ResolveNameResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wode_agent_host_v1_NetworkAgentService, 0);
