// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file wode/agent/host/v1/NetworkAgentService.proto (package wode.agent.host.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { IcmpPingRequest, IcmpPingResponse, ResolveNameRequest, ResolveNameResponse } from "./NetworkAgentService_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wode.agent.host.v1.NetworkAgentService
 */
export const NetworkAgentService = {
  typeName: "wode.agent.host.v1.NetworkAgentService",
  methods: {
    /**
     * @generated from rpc wode.agent.host.v1.NetworkAgentService.IcmpPing
     */
    icmpPing: {
      name: "IcmpPing",
      I: IcmpPingRequest,
      O: IcmpPingResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc wode.agent.host.v1.NetworkAgentService.ResolveName
     */
    resolveName: {
      name: "ResolveName",
      I: ResolveNameRequest,
      O: ResolveNameResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
