// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file wode/wecom/archive/v1/WecomArchiveService.proto (package wode.wecom.archive.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file wode/wecom/archive/v1/WecomArchiveService.proto.
 */
export const file_wode_wecom_archive_v1_WecomArchiveService: GenFile = /*@__PURE__*/
  fileDesc("Ci93b2RlL3dlY29tL2FyY2hpdmUvdjEvV2Vjb21BcmNoaXZlU2VydmljZS5wcm90bxIVd29kZS53ZWNvbS5hcmNoaXZlLnYxIvkBChhXZWNvbUFyY2hpdmVNZXNzYWdlUHJvdG8SEAoIc2VxdWVuY2UYASABKAMSDwoHY29ycF9pZBgCIAEoCRISCgptZXNzYWdlX2lkGAMgASgJEg4KBmFjdGlvbhgEIAEoCRIMCgR0eXBlGAUgASgJEiQKA3JhdxgGIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QSMAoMbWVzc2FnZV90aW1lGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIPCgdmcm9tX2lkGAggASgJEg4KBnRvX2lkcxgJIAMoCRIPCgdyb29tX2lkGAogASgJIqcBChFHZXRNZXNzYWdlUmVxdWVzdBI3CgZjbGllbnQYASABKAsyJy53b2RlLndlY29tLmFyY2hpdmUudjEuV2Vjb21DbGllbnRQcm90bxIQCghzZXF1ZW5jZRgCIAEoAxINCgVsaW1pdBgDIAEoBRINCgVwcm94eRgEIAEoCRIYChBwcm94eV9jcmVkZW50aWFsGAUgASgJEg8KB3RpbWVvdXQYBiABKAUibwoQV2Vjb21DbGllbnRQcm90bxIRCgljbGllbnRfaWQYASABKAkSDwoHY29ycF9pZBgKIAEoCRITCgtjb3JwX3NlY3JldBgLIAEoCRITCgtwcml2YXRlX2tleRgMIAEoCRINCgVwcm94eRgNIAEoCSJpChJHZXRNZXNzYWdlUmVzcG9uc2USQQoIbWVzc2FnZXMYASADKAsyLy53b2RlLndlY29tLmFyY2hpdmUudjEuV2Vjb21BcmNoaXZlTWVzc2FnZVByb3RvEhAKCHNlcXVlbmNlGAIgASgDMngKE1dlY29tQXJjaGl2ZVNlcnZpY2USYQoKR2V0TWVzc2FnZRIoLndvZGUud2Vjb20uYXJjaGl2ZS52MS5HZXRNZXNzYWdlUmVxdWVzdBopLndvZGUud2Vjb20uYXJjaGl2ZS52MS5HZXRNZXNzYWdlUmVzcG9uc2VCrAEKGWNvbS53b2RlLndlY29tLmFyY2hpdmUudjFCGFdlY29tQXJjaGl2ZVNlcnZpY2VQcm90b1ABogIDV1dBqgIVV29kZS5XZWNvbS5BcmNoaXZlLlYxygIVV29kZVxXZWNvbVxBcmNoaXZlXFYx4gIhV29kZVxXZWNvbVxBcmNoaXZlXFYxXEdQQk1ldGFkYXRh6gIYV29kZTo6V2Vjb206OkFyY2hpdmU6OlYxYgZwcm90bzM", [file_google_protobuf_struct, file_google_protobuf_timestamp]);

/**
 * @generated from message wode.wecom.archive.v1.WecomArchiveMessageProto
 */
export type WecomArchiveMessageProto = Message<"wode.wecom.archive.v1.WecomArchiveMessageProto"> & {
  /**
   * @generated from field: int64 sequence = 1;
   */
  sequence: bigint;

  /**
   * @generated from field: string corp_id = 2;
   */
  corpId: string;

  /**
   * @generated from field: string message_id = 3;
   */
  messageId: string;

  /**
   * @generated from field: string action = 4;
   */
  action: string;

  /**
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Struct raw = 6;
   */
  raw?: JsonObject | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp message_time = 7;
   */
  messageTime?: Timestamp | undefined;

  /**
   * @generated from field: string from_id = 8;
   */
  fromId: string;

  /**
   * @generated from field: repeated string to_ids = 9;
   */
  toIds: string[];

  /**
   * @generated from field: string room_id = 10;
   */
  roomId: string;
};

/**
 * Describes the message wode.wecom.archive.v1.WecomArchiveMessageProto.
 * Use `create(WecomArchiveMessageProtoSchema)` to create a new message.
 */
export const WecomArchiveMessageProtoSchema: GenMessage<WecomArchiveMessageProto> = /*@__PURE__*/
  messageDesc(file_wode_wecom_archive_v1_WecomArchiveService, 0);

/**
 * @generated from message wode.wecom.archive.v1.GetMessageRequest
 */
export type GetMessageRequest = Message<"wode.wecom.archive.v1.GetMessageRequest"> & {
  /**
   * @generated from field: wode.wecom.archive.v1.WecomClientProto client = 1;
   */
  client?: WecomClientProto | undefined;

  /**
   * @generated from field: int64 sequence = 2;
   */
  sequence: bigint;

  /**
   * @generated from field: int32 limit = 3;
   */
  limit: number;

  /**
   * @generated from field: string proxy = 4;
   */
  proxy: string;

  /**
   * @generated from field: string proxy_credential = 5;
   */
  proxyCredential: string;

  /**
   * @generated from field: int32 timeout = 6;
   */
  timeout: number;
};

/**
 * Describes the message wode.wecom.archive.v1.GetMessageRequest.
 * Use `create(GetMessageRequestSchema)` to create a new message.
 */
export const GetMessageRequestSchema: GenMessage<GetMessageRequest> = /*@__PURE__*/
  messageDesc(file_wode_wecom_archive_v1_WecomArchiveService, 1);

/**
 * @generated from message wode.wecom.archive.v1.WecomClientProto
 */
export type WecomClientProto = Message<"wode.wecom.archive.v1.WecomClientProto"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string corp_id = 10;
   */
  corpId: string;

  /**
   * @generated from field: string corp_secret = 11;
   */
  corpSecret: string;

  /**
   * @generated from field: string private_key = 12;
   */
  privateKey: string;

  /**
   * @generated from field: string proxy = 13;
   */
  proxy: string;
};

/**
 * Describes the message wode.wecom.archive.v1.WecomClientProto.
 * Use `create(WecomClientProtoSchema)` to create a new message.
 */
export const WecomClientProtoSchema: GenMessage<WecomClientProto> = /*@__PURE__*/
  messageDesc(file_wode_wecom_archive_v1_WecomArchiveService, 2);

/**
 * @generated from message wode.wecom.archive.v1.GetMessageResponse
 */
export type GetMessageResponse = Message<"wode.wecom.archive.v1.GetMessageResponse"> & {
  /**
   * @generated from field: repeated wode.wecom.archive.v1.WecomArchiveMessageProto messages = 1;
   */
  messages: WecomArchiveMessageProto[];

  /**
   * @generated from field: int64 sequence = 2;
   */
  sequence: bigint;
};

/**
 * Describes the message wode.wecom.archive.v1.GetMessageResponse.
 * Use `create(GetMessageResponseSchema)` to create a new message.
 */
export const GetMessageResponseSchema: GenMessage<GetMessageResponse> = /*@__PURE__*/
  messageDesc(file_wode_wecom_archive_v1_WecomArchiveService, 3);

/**
 * @generated from service wode.wecom.archive.v1.WecomArchiveService
 */
export const WecomArchiveService: GenService<{
  /**
   * @generated from rpc wode.wecom.archive.v1.WecomArchiveService.GetMessage
   */
  getMessage: {
    methodKind: "unary";
    input: typeof GetMessageRequestSchema;
    output: typeof GetMessageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_wode_wecom_archive_v1_WecomArchiveService, 0);
