// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file wode/wecom/archive/v1/WecomArchiveService.proto (package wode.wecom.archive.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMessageRequest, GetMessageResponse } from "./WecomArchiveService_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wode.wecom.archive.v1.WecomArchiveService
 */
export const WecomArchiveService = {
  typeName: "wode.wecom.archive.v1.WecomArchiveService",
  methods: {
    /**
     * @generated from rpc wode.wecom.archive.v1.WecomArchiveService.GetMessage
     */
    getMessage: {
      name: "GetMessage",
      I: GetMessageRequest,
      O: GetMessageResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
