// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: wode/fs/v1/FileSystemService.proto

package filesystemservicev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileKind represents the type of a file system entry
type FileKind int32

const (
	FileKind_FILE_KIND_UNSPECIFIED FileKind = 0
	FileKind_FILE_KIND_FILE        FileKind = 1
	FileKind_FILE_KIND_DIRECTORY   FileKind = 2
)

// Enum value maps for FileKind.
var (
	FileKind_name = map[int32]string{
		0: "FILE_KIND_UNSPECIFIED",
		1: "FILE_KIND_FILE",
		2: "FILE_KIND_DIRECTORY",
	}
	FileKind_value = map[string]int32{
		"FILE_KIND_UNSPECIFIED": 0,
		"FILE_KIND_FILE":        1,
		"FILE_KIND_DIRECTORY":   2,
	}
)

func (x FileKind) Enum() *FileKind {
	p := new(FileKind)
	*p = x
	return p
}

func (x FileKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileKind) Descriptor() protoreflect.EnumDescriptor {
	return file_wode_fs_v1_FileSystemService_proto_enumTypes[0].Descriptor()
}

func (FileKind) Type() protoreflect.EnumType {
	return &file_wode_fs_v1_FileSystemService_proto_enumTypes[0]
}

func (x FileKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileKind.Descriptor instead.
func (FileKind) EnumDescriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{0}
}

// FileStat represents file or directory metadata
type FileStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directory     string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`                 // Parent directory path
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                           // Full path
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                           // Entry name
	Kind          FileKind               `protobuf:"varint,4,opt,name=kind,proto3,enum=wode.fs.v1.FileKind" json:"kind,omitempty"` // Entry type
	Mtime         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=mtime,proto3" json:"mtime,omitempty"`                         // Last modification time
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`                          // Size in bytes (default: 0)
	Meta          *structpb.Struct       `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`                           // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStat) Reset() {
	*x = FileStat{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat) ProtoMessage() {}

func (x *FileStat) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat.ProtoReflect.Descriptor instead.
func (*FileStat) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{0}
}

func (x *FileStat) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *FileStat) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileStat) GetKind() FileKind {
	if x != nil {
		return x.Kind
	}
	return FileKind_FILE_KIND_UNSPECIFIED
}

func (x *FileStat) GetMtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Mtime
	}
	return nil
}

func (x *FileStat) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileStat) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ReaddirRequest lists directory contents
type ReaddirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`                                   // Directory path (required, non-empty)
	Glob          *string                `protobuf:"bytes,2,opt,name=glob,proto3,oneof" json:"glob,omitempty"`                           // Glob pattern filter
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`                      // Recursive listing (default: false)
	Depth         *int32                 `protobuf:"varint,4,opt,name=depth,proto3,oneof" json:"depth,omitempty"`                        // Maximum depth (min: 0)
	Kind          *FileKind              `protobuf:"varint,5,opt,name=kind,proto3,enum=wode.fs.v1.FileKind,oneof" json:"kind,omitempty"` // Filter by entry type
	Cursor        *string                `protobuf:"bytes,6,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`                       // Pagination cursor
	Hidden        bool                   `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`                            // Include hidden files (default: false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReaddirRequest) Reset() {
	*x = ReaddirRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReaddirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaddirRequest) ProtoMessage() {}

func (x *ReaddirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaddirRequest.ProtoReflect.Descriptor instead.
func (*ReaddirRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{1}
}

func (x *ReaddirRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *ReaddirRequest) GetGlob() string {
	if x != nil && x.Glob != nil {
		return *x.Glob
	}
	return ""
}

func (x *ReaddirRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ReaddirRequest) GetDepth() int32 {
	if x != nil && x.Depth != nil {
		return *x.Depth
	}
	return 0
}

func (x *ReaddirRequest) GetKind() FileKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return FileKind_FILE_KIND_UNSPECIFIED
}

func (x *ReaddirRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

func (x *ReaddirRequest) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

// ReaddirResponse contains directory listing
type ReaddirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FileStat            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReaddirResponse) Reset() {
	*x = ReaddirResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReaddirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaddirResponse) ProtoMessage() {}

func (x *ReaddirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaddirResponse.ProtoReflect.Descriptor instead.
func (*ReaddirResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{2}
}

func (x *ReaddirResponse) GetData() []*FileStat {
	if x != nil {
		return x.Data
	}
	return nil
}

// StatRequest gets file or directory status
type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // File or directory path
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// StatResponse contains file or directory status
type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *FileStat              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetData() *FileStat {
	if x != nil {
		return x.Data
	}
	return nil
}

// MkdirRequest creates a directory
type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                  // Directory path to create
	Recursive     *bool                  `protobuf:"varint,2,opt,name=recursive,proto3,oneof" json:"recursive,omitempty"` // Create parent directories if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{5}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetRecursive() bool {
	if x != nil && x.Recursive != nil {
		return *x.Recursive
	}
	return false
}

// MkdirResponse indicates successful directory creation
type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{6}
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Encoding      string                 `protobuf:"bytes,2,opt,name=encoding,proto3" json:"encoding,omitempty"` // base64, binary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{7}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base64        string                 `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileResponse) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// WriteFileRequest writes file contents
type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                  // File path
	Base64        string                 `protobuf:"bytes,2,opt,name=base64,proto3" json:"base64,omitempty"`              // File contents encoded as base64
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                  // File contents as bytes
	Overwrite     *bool                  `protobuf:"varint,4,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"` // Overwrite if exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{9}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

// WriteFileResponse indicates successful file write
type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{10}
}

// RenameRequest renames a file or directory
type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"` // Current path
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"` // New path
	Overwrite     *bool                  `protobuf:"varint,3,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`     // Overwrite destination if exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{11}
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *RenameRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

// RenameResponse indicates successful rename
type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{12}
}

// ExistsRequest checks if a path exists
type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Path to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{13}
}

func (x *ExistsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ExistsResponse indicates if the path exists
type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          bool                   `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"` // True if path exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{14}
}

func (x *ExistsResponse) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

// CopyRequest copies a file or directory
type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`                    // Source path
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`                  // Destination path
	Overwrite     *bool                  `protobuf:"varint,3,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"` // Overwrite destination if exists
	Shallow       *bool                  `protobuf:"varint,4,opt,name=shallow,proto3,oneof" json:"shallow,omitempty"`     // Shallow copy (for directories)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{15}
}

func (x *CopyRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *CopyRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *CopyRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

func (x *CopyRequest) GetShallow() bool {
	if x != nil && x.Shallow != nil {
		return *x.Shallow
	}
	return false
}

// CopyResponse indicates successful copy
type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{16}
}

// RemoveRequest removes a file or directory
type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                  // Path to remove
	Recursive     *bool                  `protobuf:"varint,2,opt,name=recursive,proto3,oneof" json:"recursive,omitempty"` // Recursive removal (for directories)
	Force         *bool                  `protobuf:"varint,3,opt,name=force,proto3,oneof" json:"force,omitempty"`         // Force removal (ignore errors)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil && x.Recursive != nil {
		return *x.Recursive
	}
	return false
}

func (x *RemoveRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

// RemoveResponse indicates successful removal
type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wode_fs_v1_FileSystemService_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_wode_fs_v1_FileSystemService_proto_rawDescGZIP(), []int{18}
}

var File_wode_fs_v1_FileSystemService_proto protoreflect.FileDescriptor

const file_wode_fs_v1_FileSystemService_proto_rawDesc = "" +
	"\n" +
	"\"wode/fs/v1/FileSystemService.proto\x12\n" +
	"wode.fs.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n" +
	"\bFileStat\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12(\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x14.wode.fs.v1.FileKindR\x04kind\x120\n" +
	"\x05mtime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05mtime\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12+\n" +
	"\x04meta\x18\a \x01(\v2\x17.google.protobuf.StructR\x04meta\"\xff\x01\n" +
	"\x0eReaddirRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x17\n" +
	"\x04glob\x18\x02 \x01(\tH\x00R\x04glob\x88\x01\x01\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12\x19\n" +
	"\x05depth\x18\x04 \x01(\x05H\x01R\x05depth\x88\x01\x01\x12-\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x14.wode.fs.v1.FileKindH\x02R\x04kind\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\x06 \x01(\tH\x03R\x06cursor\x88\x01\x01\x12\x16\n" +
	"\x06hidden\x18\a \x01(\bR\x06hiddenB\a\n" +
	"\x05_globB\b\n" +
	"\x06_depthB\a\n" +
	"\x05_kindB\t\n" +
	"\a_cursor\";\n" +
	"\x0fReaddirResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.wode.fs.v1.FileStatR\x04data\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"8\n" +
	"\fStatResponse\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.wode.fs.v1.FileStatR\x04data\"S\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\trecursive\x18\x02 \x01(\bH\x00R\trecursive\x88\x01\x01B\f\n" +
	"\n" +
	"_recursive\"\x0f\n" +
	"\rMkdirResponse\"A\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\tR\bencoding\"D\n" +
	"\x10ReadFileResponse\x12\x16\n" +
	"\x06base64\x18\x01 \x01(\tR\x06base64\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x83\x01\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06base64\x18\x02 \x01(\tR\x06base64\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\toverwrite\x18\x04 \x01(\bH\x00R\toverwrite\x88\x01\x01B\f\n" +
	"\n" +
	"_overwrite\"\x13\n" +
	"\x11WriteFileResponse\"v\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\x12!\n" +
	"\toverwrite\x18\x03 \x01(\bH\x00R\toverwrite\x88\x01\x01B\f\n" +
	"\n" +
	"_overwrite\"\x10\n" +
	"\x0eRenameResponse\"#\n" +
	"\rExistsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"$\n" +
	"\x0eExistsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\bR\x04data\"\x8f\x01\n" +
	"\vCopyRequest\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12!\n" +
	"\toverwrite\x18\x03 \x01(\bH\x00R\toverwrite\x88\x01\x01\x12\x1d\n" +
	"\ashallow\x18\x04 \x01(\bH\x01R\ashallow\x88\x01\x01B\f\n" +
	"\n" +
	"_overwriteB\n" +
	"\n" +
	"\b_shallow\"\x0e\n" +
	"\fCopyResponse\"y\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\trecursive\x18\x02 \x01(\bH\x00R\trecursive\x88\x01\x01\x12\x19\n" +
	"\x05force\x18\x03 \x01(\bH\x01R\x05force\x88\x01\x01B\f\n" +
	"\n" +
	"_recursiveB\b\n" +
	"\x06_force\"\x10\n" +
	"\x0eRemoveResponse*R\n" +
	"\bFileKind\x12\x19\n" +
	"\x15FILE_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFILE_KIND_FILE\x10\x01\x12\x17\n" +
	"\x13FILE_KIND_DIRECTORY\x10\x022\xc4\x06\n" +
	"\x11FileSystemService\x12]\n" +
	"\aReaddir\x12\x1a.wode.fs.v1.ReaddirRequest\x1a\x1b.wode.fs.v1.ReaddirResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/fs/readdir\x12N\n" +
	"\x04Stat\x12\x17.wode.fs.v1.StatRequest\x1a\x18.wode.fs.v1.StatResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/fs/stat\x12U\n" +
	"\x05Mkdir\x12\x18.wode.fs.v1.MkdirRequest\x1a\x19.wode.fs.v1.MkdirResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/fs/mkdir\x12a\n" +
	"\bReadFile\x12\x1b.wode.fs.v1.ReadFileRequest\x1a\x1c.wode.fs.v1.ReadFileResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/fs/readFile\x12e\n" +
	"\tWriteFile\x12\x1c.wode.fs.v1.WriteFileRequest\x1a\x1d.wode.fs.v1.WriteFileResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/fs/writeFile\x12Y\n" +
	"\x06Rename\x12\x19.wode.fs.v1.RenameRequest\x1a\x1a.wode.fs.v1.RenameResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/fs/rename\x12V\n" +
	"\x06Exists\x12\x19.wode.fs.v1.ExistsRequest\x1a\x1a.wode.fs.v1.ExistsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/fs/exists\x12Q\n" +
	"\x04Copy\x12\x17.wode.fs.v1.CopyRequest\x1a\x18.wode.fs.v1.CopyResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/fs/copy\x12Y\n" +
	"\x06Remove\x12\x19.wode.fs.v1.RemoveRequest\x1a\x1a.wode.fs.v1.RemoveResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/fs/removeB\xb5\x01\n" +
	"\x0ecom.wode.fs.v1B\x16FileSystemServiceProtoP\x01ZAgithub.com/wenerme/wode/wogo/proto/wode/fs/v1;filesystemservicev1\xa2\x02\x03WFX\xaa\x02\n" +
	"Wode.Fs.V1\xca\x02\n" +
	"Wode\\Fs\\V1\xe2\x02\x16Wode\\Fs\\V1\\GPBMetadata\xea\x02\fWode::Fs::V1b\x06proto3"

var (
	file_wode_fs_v1_FileSystemService_proto_rawDescOnce sync.Once
	file_wode_fs_v1_FileSystemService_proto_rawDescData []byte
)

func file_wode_fs_v1_FileSystemService_proto_rawDescGZIP() []byte {
	file_wode_fs_v1_FileSystemService_proto_rawDescOnce.Do(func() {
		file_wode_fs_v1_FileSystemService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wode_fs_v1_FileSystemService_proto_rawDesc), len(file_wode_fs_v1_FileSystemService_proto_rawDesc)))
	})
	return file_wode_fs_v1_FileSystemService_proto_rawDescData
}

var file_wode_fs_v1_FileSystemService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wode_fs_v1_FileSystemService_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_wode_fs_v1_FileSystemService_proto_goTypes = []any{
	(FileKind)(0),                 // 0: wode.fs.v1.FileKind
	(*FileStat)(nil),              // 1: wode.fs.v1.FileStat
	(*ReaddirRequest)(nil),        // 2: wode.fs.v1.ReaddirRequest
	(*ReaddirResponse)(nil),       // 3: wode.fs.v1.ReaddirResponse
	(*StatRequest)(nil),           // 4: wode.fs.v1.StatRequest
	(*StatResponse)(nil),          // 5: wode.fs.v1.StatResponse
	(*MkdirRequest)(nil),          // 6: wode.fs.v1.MkdirRequest
	(*MkdirResponse)(nil),         // 7: wode.fs.v1.MkdirResponse
	(*ReadFileRequest)(nil),       // 8: wode.fs.v1.ReadFileRequest
	(*ReadFileResponse)(nil),      // 9: wode.fs.v1.ReadFileResponse
	(*WriteFileRequest)(nil),      // 10: wode.fs.v1.WriteFileRequest
	(*WriteFileResponse)(nil),     // 11: wode.fs.v1.WriteFileResponse
	(*RenameRequest)(nil),         // 12: wode.fs.v1.RenameRequest
	(*RenameResponse)(nil),        // 13: wode.fs.v1.RenameResponse
	(*ExistsRequest)(nil),         // 14: wode.fs.v1.ExistsRequest
	(*ExistsResponse)(nil),        // 15: wode.fs.v1.ExistsResponse
	(*CopyRequest)(nil),           // 16: wode.fs.v1.CopyRequest
	(*CopyResponse)(nil),          // 17: wode.fs.v1.CopyResponse
	(*RemoveRequest)(nil),         // 18: wode.fs.v1.RemoveRequest
	(*RemoveResponse)(nil),        // 19: wode.fs.v1.RemoveResponse
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 21: google.protobuf.Struct
}
var file_wode_fs_v1_FileSystemService_proto_depIdxs = []int32{
	0,  // 0: wode.fs.v1.FileStat.kind:type_name -> wode.fs.v1.FileKind
	20, // 1: wode.fs.v1.FileStat.mtime:type_name -> google.protobuf.Timestamp
	21, // 2: wode.fs.v1.FileStat.meta:type_name -> google.protobuf.Struct
	0,  // 3: wode.fs.v1.ReaddirRequest.kind:type_name -> wode.fs.v1.FileKind
	1,  // 4: wode.fs.v1.ReaddirResponse.data:type_name -> wode.fs.v1.FileStat
	1,  // 5: wode.fs.v1.StatResponse.data:type_name -> wode.fs.v1.FileStat
	2,  // 6: wode.fs.v1.FileSystemService.Readdir:input_type -> wode.fs.v1.ReaddirRequest
	4,  // 7: wode.fs.v1.FileSystemService.Stat:input_type -> wode.fs.v1.StatRequest
	6,  // 8: wode.fs.v1.FileSystemService.Mkdir:input_type -> wode.fs.v1.MkdirRequest
	8,  // 9: wode.fs.v1.FileSystemService.ReadFile:input_type -> wode.fs.v1.ReadFileRequest
	10, // 10: wode.fs.v1.FileSystemService.WriteFile:input_type -> wode.fs.v1.WriteFileRequest
	12, // 11: wode.fs.v1.FileSystemService.Rename:input_type -> wode.fs.v1.RenameRequest
	14, // 12: wode.fs.v1.FileSystemService.Exists:input_type -> wode.fs.v1.ExistsRequest
	16, // 13: wode.fs.v1.FileSystemService.Copy:input_type -> wode.fs.v1.CopyRequest
	18, // 14: wode.fs.v1.FileSystemService.Remove:input_type -> wode.fs.v1.RemoveRequest
	3,  // 15: wode.fs.v1.FileSystemService.Readdir:output_type -> wode.fs.v1.ReaddirResponse
	5,  // 16: wode.fs.v1.FileSystemService.Stat:output_type -> wode.fs.v1.StatResponse
	7,  // 17: wode.fs.v1.FileSystemService.Mkdir:output_type -> wode.fs.v1.MkdirResponse
	9,  // 18: wode.fs.v1.FileSystemService.ReadFile:output_type -> wode.fs.v1.ReadFileResponse
	11, // 19: wode.fs.v1.FileSystemService.WriteFile:output_type -> wode.fs.v1.WriteFileResponse
	13, // 20: wode.fs.v1.FileSystemService.Rename:output_type -> wode.fs.v1.RenameResponse
	15, // 21: wode.fs.v1.FileSystemService.Exists:output_type -> wode.fs.v1.ExistsResponse
	17, // 22: wode.fs.v1.FileSystemService.Copy:output_type -> wode.fs.v1.CopyResponse
	19, // 23: wode.fs.v1.FileSystemService.Remove:output_type -> wode.fs.v1.RemoveResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_wode_fs_v1_FileSystemService_proto_init() }
func file_wode_fs_v1_FileSystemService_proto_init() {
	if File_wode_fs_v1_FileSystemService_proto != nil {
		return
	}
	file_wode_fs_v1_FileSystemService_proto_msgTypes[1].OneofWrappers = []any{}
	file_wode_fs_v1_FileSystemService_proto_msgTypes[5].OneofWrappers = []any{}
	file_wode_fs_v1_FileSystemService_proto_msgTypes[9].OneofWrappers = []any{}
	file_wode_fs_v1_FileSystemService_proto_msgTypes[11].OneofWrappers = []any{}
	file_wode_fs_v1_FileSystemService_proto_msgTypes[15].OneofWrappers = []any{}
	file_wode_fs_v1_FileSystemService_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wode_fs_v1_FileSystemService_proto_rawDesc), len(file_wode_fs_v1_FileSystemService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wode_fs_v1_FileSystemService_proto_goTypes,
		DependencyIndexes: file_wode_fs_v1_FileSystemService_proto_depIdxs,
		EnumInfos:         file_wode_fs_v1_FileSystemService_proto_enumTypes,
		MessageInfos:      file_wode_fs_v1_FileSystemService_proto_msgTypes,
	}.Build()
	File_wode_fs_v1_FileSystemService_proto = out.File
	file_wode_fs_v1_FileSystemService_proto_goTypes = nil
	file_wode_fs_v1_FileSystemService_proto_depIdxs = nil
}
