import { z } from 'zod/v4';
import type { EnumValues } from './types';

export const ResourceActionType = Object.freeze({
	__proto__: null,
	Approve: 'Approve',
	AssignOwner: 'AssignOwner',
	Bind: 'Bind',
	BindCustomer: 'BindCustomer',
	BindEntity: 'BindEntity',
	BindUser: 'BindUser',
	Cancel: 'Cancel',
	ChangePassword: 'ChangePassword',
	ClaimOwner: 'ClaimOwner',
	Close: 'Close',
	Communicate: 'Communicate',
	Complete: 'Complete',
	Create: 'Create',
	Delete: 'Delete',
	Deny: 'Deny',
	Disable: 'Disable',
	Download: 'Download',
	Edit: 'Edit',
	Enable: 'Enable',
	List: 'List',
	Login: 'Login',
	Logout: 'Logout',
	Manage: 'Manage',
	Publish: 'Publish',
	Purge: 'Purge',
	Read: 'Read',
	Reject: 'Reject',
	ReleaseOwner: 'ReleaseOwner',
	ResetPassword: 'ResetPassword',
	ReturnForRevision: 'ReturnForRevision',
	Revise: 'Revise',
	SaveDraft: 'SaveDraft',
	Signup: 'Signup',
	Submit: 'Submit',
	SubmitAgency: 'SubmitAgency',
	SubmitVendor: 'SubmitVendor',
	Suspend: 'Suspend',
	Terminate: 'Terminate',
	Timeout: 'Timeout',
	Unbind: 'Unbind',
	UnbindCustomer: 'UnbindCustomer',
	UnbindEntity: 'UnbindEntity',
	UnbindUser: 'UnbindUser',
	Undelete: 'Undelete',
	Unpublish: 'Unpublish',
	Update: 'Update',
	UpdateNotes: 'UpdateNotes',
	UpdateTags: 'UpdateTags',
	Upload: 'Upload',
	Validate: 'Validate',
	View: 'View',
	Write: 'Write',
} as const);
export type ResourceActionType = EnumValues<typeof ResourceActionType>;
export const ResourceActionTypeSchema = z
	.union([
		z.literal(ResourceActionType.Approve).describe('批准'),
		z.literal(ResourceActionType.AssignOwner).describe('分配负责人'),
		z.literal(ResourceActionType.Bind).describe('绑定'),
		z.literal(ResourceActionType.BindCustomer).describe('绑定客户'),
		z.literal(ResourceActionType.BindEntity).describe('绑定实体'),
		z.literal(ResourceActionType.BindUser).describe('绑定用户'),
		z.literal(ResourceActionType.Cancel).describe('取消'),
		z.literal(ResourceActionType.ChangePassword).describe('修改密码'),
		z.literal(ResourceActionType.ClaimOwner).describe('认领负责人'),
		z.literal(ResourceActionType.Close).describe('关闭'),
		z.literal(ResourceActionType.Communicate).describe('沟通'),
		z.literal(ResourceActionType.Complete).describe('完成'),
		z.literal(ResourceActionType.Create).describe('创建'),
		z.literal(ResourceActionType.Delete).describe('删除'),
		z.literal(ResourceActionType.Deny).describe('拒绝'),
		z.literal(ResourceActionType.Disable).describe('禁用'),
		z.literal(ResourceActionType.Download).describe('下载'),
		z.literal(ResourceActionType.Edit).describe('编辑'),
		z.literal(ResourceActionType.Enable).describe('启用'),
		z.literal(ResourceActionType.List).describe('列表'),
		z.literal(ResourceActionType.Login).describe('登录'),
		z.literal(ResourceActionType.Logout).describe('登出'),
		z.literal(ResourceActionType.Manage).describe('管理'),
		z.literal(ResourceActionType.Publish).describe('发布'),
		z.literal(ResourceActionType.Purge).describe('彻底删除'),
		z.literal(ResourceActionType.Read).describe('读取'),
		z.literal(ResourceActionType.Reject).describe('驳回'),
		z.literal(ResourceActionType.ReleaseOwner).describe('释放负责人'),
		z.literal(ResourceActionType.ResetPassword).describe('重置密码'),
		z.literal(ResourceActionType.ReturnForRevision).describe('退回修订'),
		z.literal(ResourceActionType.Revise).describe('修订'),
		z.literal(ResourceActionType.SaveDraft).describe('保存草稿'),
		z.literal(ResourceActionType.Signup).describe('注册'),
		z.literal(ResourceActionType.Submit).describe('提交'),
		z.literal(ResourceActionType.SubmitAgency).describe('提交机构'),
		z.literal(ResourceActionType.SubmitVendor).describe('提交供应商'),
		z.literal(ResourceActionType.Suspend).describe('暂停'),
		z.literal(ResourceActionType.Terminate).describe('终止'),
		z.literal(ResourceActionType.Timeout).describe('超时'),
		z.literal(ResourceActionType.Unbind).describe('解绑'),
		z.literal(ResourceActionType.UnbindCustomer).describe('解绑客户'),
		z.literal(ResourceActionType.UnbindEntity).describe('解绑实体'),
		z.literal(ResourceActionType.UnbindUser).describe('解绑用户'),
		z.literal(ResourceActionType.Undelete).describe('恢复删除'),
		z.literal(ResourceActionType.Unpublish).describe('取消发布'),
		z.literal(ResourceActionType.Update).describe('更新'),
		z.literal(ResourceActionType.UpdateNotes).describe('修改备注'),
		z.literal(ResourceActionType.UpdateNotes).describe('更新备注'),
		z.literal(ResourceActionType.UpdateTags).describe('更新标签'),
		z.literal(ResourceActionType.Upload).describe('上传'),
		z.literal(ResourceActionType.Validate).describe('校验'),
		z.literal(ResourceActionType.View).describe('查看'),
		z.literal(ResourceActionType.Write).describe('写入'),
	])
	.meta({
		title: 'ResourceAction',
		description: '资源操作',
		type: 'string',
	});
export const ResourceActionDataSchema = z.object({
	reason: z.string().optional().describe('操作原因'),
});
