import { Drain } from './Drain';
import type { LogCluster } from './LogCluster';
import type { PersistenceHandler } from './persistence/PersistenceHandler';
import type { ClusterUpdateType, ExtractedParameter, SearchStrategy } from './types';

/**
 * High-level API for log template mining with persistence support.
 *
 * TemplateMiner wraps the Drain algorithm and provides convenience methods
 * for extracting parameters and managing persistence.
 */
export class TemplateMiner {
	constructor(
		private drain: Drain,
		private readonly persistence: PersistenceHandler,
	) {}

	/**
	 * Adds a log message and returns the update type, cluster, template, and cluster count.
	 *
	 * @param content The log message content
	 * @returns Object containing updateType, cluster, templateMined, and clusterCount
	 */
	async addLogMessage(content: string): Promise<{
		updateType: ClusterUpdateType;
		cluster: LogCluster;
		templateMined: string;
		clusterCount: number;
	}> {
		const { cluster, updateType } = this.drain.addLogMessage(content);

		const templateMined = cluster.getTemplate();
		const clusterCount = this.drain.getClusters().length;

		if (updateType !== 'none') {
			await this.saveState();
		}

		return {
			updateType,
			cluster,
			templateMined,
			clusterCount,
		};
	}

	/**
	 * Matches a log message against an already existing cluster.
	 *
	 * @param content Log message to match
	 * @param strategy Search strategy
	 * @returns Matched cluster or null
	 */
	match(content: string, strategy: SearchStrategy = 'never'): LogCluster | null {
		return this.drain.match(content, strategy);
	}

	/**
	 * Extracts parameters from a log message according to a provided template.
	 *
	 * @param logTemplate Template generated by AddLogMessage
	 * @param logMessage The log message to extract parameters from
	 * @returns Array of extracted parameters, or null if template doesn't match
	 */
	extractParameters(logTemplate: string, logMessage: string): ExtractedParameter[] | null {
		// Apply delimiters
		let processedMessage = logMessage;
		for (const delimiter of this.drain.extraDelimiters) {
			// Escape delimiter for regex if it contains special characters
			const escapedDelimiter = delimiter.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
			processedMessage = processedMessage.replace(new RegExp(escapedDelimiter, 'g'), ' ');
		}

		const { templateRegex, paramGroupNameToMaskName } = this.getTemplateParameterExtractionRegex(logTemplate);

		// Create regex from template
		const regex = new RegExp(templateRegex);

		// Match the log message against the template
		const match = processedMessage.match(regex);

		// Template doesn't match
		if (match === null) {
			return null;
		}

		// Extract named captures
		const extractedParameters: ExtractedParameter[] = [];

		// Get all named groups from the match
		if (match.groups) {
			for (const [groupName, value] of Object.entries(match.groups)) {
				if (value !== undefined) {
					const maskName = paramGroupNameToMaskName.get(groupName);
					if (maskName !== undefined) {
						extractedParameters.push({
							value,
							maskName,
						});
					}
				}
			}
		}

		// Also check by index if groups are not available (fallback)
		// The regex exec method provides better named group support
		const execResult = regex.exec(processedMessage);
		if (execResult !== null && execResult.groups === undefined) {
			// Fallback: extract by order (less reliable but works)
			const indices = Array.from({ length: execResult.length - 1 }, (_, i) => i + 1);
			let paramIndex = 0;
			for (const index of indices) {
				const value = execResult[index];
				if (value !== undefined) {
					// Find corresponding mask name by order
					// This is a fallback - ideally we should use named groups
					const maskName = paramGroupNameToMaskName.get(`p_${paramIndex}`);
					if (maskName !== undefined) {
						extractedParameters.push({
							value,
							maskName,
						});
					}
					paramIndex++;
				}
			}
		}

		return extractedParameters.length > 0 ? extractedParameters : null;
	}

	/**
	 * Gets the template parameter extraction regex and mapping.
	 *
	 * @param logTemplate The log template
	 * @returns Tuple of [templateRegex, paramGroupNameToMaskName]
	 */
	private getTemplateParameterExtractionRegex(logTemplate: string): {
		templateRegex: string;
		paramGroupNameToMaskName: Map<string, string>;
	} {
		const paramGroupNameToMaskName = new Map<string, string>();
		let paramNameCounter = 0;

		const getNextParamName = (): string => {
			const paramGroupName = `p_${paramNameCounter}`;
			paramNameCounter++;
			return paramGroupName;
		};

		// Create a named group with the respective patterns for the given mask-name
		const createCaptureRegex = (maskName: string): string => {
			const allowedPatterns: string[] = [];

			if (maskName === '*') {
				allowedPatterns.push('.+?');
			}

			// Give each capture group a unique name to avoid conflict
			const paramGroupName = getNextParamName();
			paramGroupNameToMaskName.set(paramGroupName, maskName);
			const joinedPatterns = allowedPatterns.join('|');
			const captureRegex = `(?<${paramGroupName}>${joinedPatterns})`;

			return captureRegex;
		};

		// For every mask in the template, replace it with a named group
		const maskNames = new Set<string>();
		// The drain catch-all mask
		maskNames.add('*');

		// Escape the template for regex
		let templateRegex = this.escapeRegex(logTemplate);

		// Replace each mask name with a proper regex that captures it
		for (const maskName of maskNames) {
			const searchStr = `<${this.escapeRegex(maskName)}>`;

			// Replace one-by-one to get a new param group name for each replacement
			while (true) {
				const repStr = createCaptureRegex(maskName);
				const templateRegexNew = templateRegex.replace(searchStr, repStr);
				// Break when all replaces for this mask are done
				if (templateRegexNew === templateRegex) {
					break;
				}
				templateRegex = templateRegexNew;
			}
		}

		// Match also messages with multiple spaces or other whitespace chars between tokens
		templateRegex = templateRegex.replace(/\\ /g, '\\s+');
		templateRegex = `^${templateRegex}$`;

		return { templateRegex, paramGroupNameToMaskName };
	}

	/**
	 * Escapes special regex characters in a string.
	 */
	private escapeRegex(str: string): string {
		return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	}

	/**
	 * Loads the Drain state from persistence.
	 *
	 * @throws Error if loading fails
	 */
	async loadState(): Promise<void> {
		const state = await this.persistence.load();
		if (state === null || (typeof state === 'string' && state.length === 0)) {
			throw new Error('saved state not found');
		}

		try {
			const stateStr = typeof state === 'string' ? state : new TextDecoder().decode(state);
			const data = JSON.parse(stateStr);
			this.drain = Drain.fromJSON(data);
		} catch (error) {
			throw new Error(`failed to unmarshal state: ${error instanceof Error ? error.message : String(error)}`);
		}
	}

	/**
	 * Saves the Drain state to persistence.
	 *
	 * @throws Error if saving fails
	 */
	async saveState(): Promise<void> {
		try {
			const state = JSON.stringify(this.drain.toJSON());
			await this.persistence.save(state);
		} catch (error) {
			throw new Error(`failed to save state: ${error instanceof Error ? error.message : String(error)}`);
		}
	}

	/**
	 * Gets the underlying Drain instance.
	 */
	getDrain(): Drain {
		return this.drain;
	}
}
