// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file wode/resource/v1/ResourceService.proto (package wode.resource.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ResourceServiceCreateRequest, ResourceServiceCreateResponse, ResourceServiceDeleteRequest, ResourceServiceDeleteResponse, ResourceServiceGetRequest, ResourceServiceGetResponse, ResourceServiceListRequest, ResourceServiceListResponse, ResourceServiceUpdateRequest, ResourceServiceUpdateResponse } from "./ResourceService_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wode.resource.v1.ResourceService
 */
export const ResourceService = {
  typeName: "wode.resource.v1.ResourceService",
  methods: {
    /**
     * @generated from rpc wode.resource.v1.ResourceService.Get
     */
    get: {
      name: "Get",
      I: ResourceServiceGetRequest,
      O: ResourceServiceGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.v1.ResourceService.List
     */
    list: {
      name: "List",
      I: ResourceServiceListRequest,
      O: ResourceServiceListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.v1.ResourceService.Delete
     */
    delete: {
      name: "Delete",
      I: ResourceServiceDeleteRequest,
      O: ResourceServiceDeleteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.v1.ResourceService.Create
     */
    create: {
      name: "Create",
      I: ResourceServiceCreateRequest,
      O: ResourceServiceCreateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.resource.v1.ResourceService.Update
     */
    update: {
      name: "Update",
      I: ResourceServiceUpdateRequest,
      O: ResourceServiceUpdateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
