// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file wode/storage/object/v1/ObjectStorageService.proto (package wode.storage.object.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ComposeObjectRequest, ComposeObjectResponse, CopyObjectRequest, CopyObjectResponse, GetObjectRequest, GetObjectResponse, GetObjectStreamRequest, GetObjectStreamResponse, ListBucketRequest, ListBucketResponse, ListObjectRequest, ListObjectResponse, MakeBucketRequest, MakeBucketResponse, PutObjectRequest, PutObjectResponse, PutObjectStreamRequest, PutObjectStreamResponse, RemoveObjectRequest, RemoveObjectResponse, StatObjectRequest, StatObjectResponse } from "./ObjectStorageService_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service wode.storage.object.v1.ObjectStorageService
 */
export const ObjectStorageService = {
  typeName: "wode.storage.object.v1.ObjectStorageService",
  methods: {
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.ListBucket
     */
    listBucket: {
      name: "ListBucket",
      I: ListBucketRequest,
      O: ListBucketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.MakeBucket
     */
    makeBucket: {
      name: "MakeBucket",
      I: MakeBucketRequest,
      O: MakeBucketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.GetObject
     */
    getObject: {
      name: "GetObject",
      I: GetObjectRequest,
      O: GetObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.GetObjectStream
     */
    getObjectStream: {
      name: "GetObjectStream",
      I: GetObjectStreamRequest,
      O: GetObjectStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.ListObject
     */
    listObject: {
      name: "ListObject",
      I: ListObjectRequest,
      O: ListObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.PutObject
     */
    putObject: {
      name: "PutObject",
      I: PutObjectRequest,
      O: PutObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.PutObjectStream
     */
    putObjectStream: {
      name: "PutObjectStream",
      I: PutObjectStreamRequest,
      O: PutObjectStreamResponse,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.ComposeObject
     */
    composeObject: {
      name: "ComposeObject",
      I: ComposeObjectRequest,
      O: ComposeObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.CopyObject
     */
    copyObject: {
      name: "CopyObject",
      I: CopyObjectRequest,
      O: CopyObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.StatObject
     */
    statObject: {
      name: "StatObject",
      I: StatObjectRequest,
      O: StatObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc wode.storage.object.v1.ObjectStorageService.RemoveObject
     */
    removeObject: {
      name: "RemoveObject",
      I: RemoveObjectRequest,
      O: RemoveObjectResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
